### ISSUE TITLE
Integration into fdroid

### ISSUE THREAD

**Issue by jsparber** [yeriomin/YalpStore#111]
It would be awesome if YalpStore could create a local fdroid binary repository.
So we would get automatic updates and all features from fdroid.
I know fdroid is not intended to download proprietary software but it would be a easy solution, to get rid of google play store or Aptoide and other proprietary app store replacements.
Google play store has a lot of apps so maybe the user should decide which apps he wants in the repository.

**Comment by yeriomin** [comment]
Hello! Thanks for the suggestion, but I don't see how this would work right now. Could you be more specific?

* F-droid repo needs a predefined list of apps. There is no way to get a list of all apps from Play Store.
* F-droid repo is a python web service, so it would be really hard to make it "local" (run on user's device), as far as I know.
* Even if it was, it is going to be just an extra layer of code (and bugs) between Play Store and the user. It's not going to make the whole system free from proprietary code. I wrote Yalp to be able to get apks *directly* from Play Store, so that there would be no doubts like "is it really the latest version?" or "is it really that app?" which I always have when I use the apk aggregators.

**Comment by jsparber** [comment]
- I didn't knew that you can not get a complete list of apps. OK that would not work for that many apps, but maybe we could just generate a list of local installed apps. 
- Yes somebody has to write the server in java for android, I didn't  thought about that.
- Yes, I see that problem too. 

Maybe it's not that good of an idea.
Mostly I thought about an easy way to get auto/background updates.

**Comment by yeriomin** [comment]
Auto/background updates are in master (with root, though), and will be out with v0.12. Issue #44.

Also, f-droid doesn't do background updates, as far as I know. Only checks.

**Comment by jsparber** [comment]
Cool, but I don't like to have my phone rooted.
F-droid does support background updates throw the [privileged fdroid extension](https://gitlab.com/fdroid/privileged-extension). Which is a small app you have to flash via recovery.
