### ISSUE TITLE
YalpStore and main Google account

### ISSUE THREAD

**Issue by justmix4** [yeriomin/YalpStore#125]
Hello Sergey. 
Unfortunately, the Blankstore application is no longer supported so the community needs an alternative like YalpStore.
I would like to use your app, but I'm a bit afraid of ban from Google. Forgive me, I'm a little paranoid. 
I have such an idea, please take a look at this. 

Introduction:
When we first time launch Play Store each of us should accept the Google Play Terms of Service before using this application. We will return to this later. 

Steps:
1) The first part of the plan is to install FakeStore. This is part of the microG project which of course is required for FS to work. This empty 'application' pretends Play Store.
https://github.com/microg/android_packages_apps_FakeStore

2) The next step is to launch the Play Store and accept the ToS.

3) So when we installed FakeStore and we accepted ToS .. I think we can remove the Play Store. Please remember: theoretically, the Play Store is still in the system as FakeStore

4) Time to install YalpStore. We sign in with our main Google Account and we have a ready-to-use app.

In my opinion, Google theoretically sees YalpStore as a Play Store. Thanks to FakeStore. Also, in my opinion, we didn't break the Terms of Service in this history.  I was wondering if this could reduce the risk of ban. Unfortunately I'm not a developer and I'm not able to say if it makes sense. However, I wanted to share with you and the community my thoughts. I am curious about your opinion of this. By the way thanks for your work and good luck in the future. Please forgive me so many repetitions, English is not my native language. Best regards.

**Comment by yeriomin** [comment]
Hello!

Thank you for your kind words. I understand your concern, but the risk is mostly theoretical. It is definitely illegal to use Yalp Store, but I have never heard about actual bans. Software like Yalp Store has existed since Play Store started working.

"Google theoretically sees YalpStore as a Play Store." Yalp Store is a reverse-engineered software, so it is impossible to directly distinguish Yalp from Play. The fact that it works means that Google is not bothered by Yalp's (or other similar tools) existence. They don't care.

"Thanks to FakeStore." As far as I can see from its sources, it is a stub which has the same package name and optionally the same signature as a real Play Store, but does zero actual work. Neither google servers nor Yalp Store app know or care about its existence, so having or not having it does not change your chances of being banned.

"we didn't break the Terms of Service in this history" ToS states that it is illegal to access Google Play Store servers using anything except an official Play Store app, so **any** usage of Yalp Store is illegal, no matter how or when.

The best way to reduce the risk of a ban is not using your own account. Currently, the only reason why you would need to do it is to be able to download the apps you have **purchased**. It is both safe and sufficient to use Yalp-provided account in all other cases. My advice is to just install Yalp Store without any google apps and use it with Yalp-provided account. This way you share no information with google, except your device config (technical info for app compatibility checks, they will never know which real account you use). Registering a fake account (and accepting ToS) for Yalp Store is redundant at this point.

**Comment by justmix4** [comment]
Thank you for your answer. After reading this and thinking about it, I decided to start using YalpStore with Yalp-provided account.  
By the way, I wanted to say that I finished Polish translation on POEditor. I hope you will soon implement them in your application.

**Comment by yeriomin** [comment]
Thank you. Added your translation to master. It will be out with v0.14.

**Comment by justmix4** [comment]
Great, I can not wait!

I corrected many minor mistakes, sorry for bothering you. Now the translation is 100% correct.
https://github.com/justmix4/YalpStore/commit/bab6a98f4e80ac1edf64525c16ccf19ab3600729

**Comment by justmix4** [comment]
Up
