### ISSUE TITLE
Android 7.1.1, apps stuck trying to download

### ISSUE THREAD

**Issue by mission712** [yeriomin/YalpStore#162]
### Expected behaviour
The apps to download

### Actual behaviour
The apps get stuck trying to download forever

### Steps to reproduce
1. Install Yalp Store on Android 7.1.1
2. Try to install an app through

### Info about your device
Samsung GT-I9300 (Galaxy S3 International)
Android 7.1.1, Resurrection Remix Nightly

### Image of Downloads section
![screenshot_20170514-221850](https://cloud.githubusercontent.com/assets/14175669/26037026/53404ee0-38f3-11e7-8958-0c53ee3e86cb.png)

**Comment by syl3nt** [comment]
Dude.. you are on a vpn .. turn it off and try again ..

**Comment by mission712** [comment]
Thanks. That worked.
Note: technically, it's not a VPN, it's an app called "DNS Changer" that allows me to change my DNS when on a mobile network. Is there any other app that allows me to change my DNS without a VPN? thanks.

**Comment by yeriomin** [comment]
@syl3nt Thanks, it would take me a **long** time to notice that key icon.
@mission712 It might not be a VPN *functionally*, but *technically* it is. The problem is not with VPN in general, but probably with your VPN provider specifically. You could try [DNSSetter](https://f-droid.org/repository/browse/?fdfilter=dnssetter&fdid=be.brunoparmentier.dnssetter) or [DNS man](https://f-droid.org/repository/browse/?fdfilter=dns&fdid=io.github.otakuchiyan.dnsman) (root required). [DNS66](https://f-droid.org/repository/browse/?fdfilter=dns&fdid=org.jak_linux.dns66) would also work, but it poses as an ad blocker.
