### ISSUE TITLE
Crashes when trying to get list of updates

### ISSUE THREAD

**Issue by teod0r** [yeriomin/YalpStore#172]
Since version 0.14 Yalp Store crashes when trying to get list of updates

**Comment by yeriomin** [comment]
[v0.15](https://f-droid.org/repository/browse/?fdid=com.github.yeriomin.yalpstore) has been available for some time. If it is still happening in v0.15, please use the built-in crash reporter. It sends me a letter with the exception stack trace, logs and device info. Or you can get it all from your device by hand and post here. Also, the issue template is not random, it forces you to try to explain the specific cause of the crash. "Crash on the main page" is unhelpful, sorry.

**Comment by teod0r** [comment]
в 0.15 то же самое. диалога отправки репорта при краше нет

**Comment by haverholm** [comment]
Fwiw, I find no built-in crash reporter in the F-droid version 0.15 (if that's even different from other builds).

I do, however, have trouble logging in with a fake Yalp account, so am getting no updates or even search results. Not a crash, but renders the app useless.

Lineage 14.1-20170501-NIGHTLY-bacon without Gapps

**Comment by syl3nt** [comment]
Ahm, you want to go to about, press on the dev. E-mail, and it should bring up your email app with the report inside ready to be sent

**Comment by yeriomin** [comment]
@teod0r You seem to be ignoring what I'm saying

@haverholm 
>I find no built-in crash reporter

Crash report window is shown when Yalp crashes. You can send me a letter with your device info and logs if you click on the developer's email link on the About page.

>have trouble logging in

To log in using a built-in account I'm using a small service hosted on a free hosting. Looks like google is randomly denying logins from there due to too many login attempts. I will probably deploy more token dispensers. Somewhere.

You can use your own account (I recommend creating a throwaway). Or just try a couple of times more, it will log in eventually.

**Comment by haverholm** [comment]
>just try a couple of times more, it will log in eventually.

"Eventually" is pretty open-ended, though. I've been tapping away 10-20 times every now and then since you suggested it, but to no effect. Looks like Google is on to you ;p

**Comment by teod0r** [comment]
чё закрыл? в 0.16 то же самое

**Comment by teod0r** [comment]
а 0.17 крашится при старте
