### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by syl3nt** [yeriomin/YalpStore#173]
Wouldn't it be possible to translate the apps  categories as well?

**Comment by yeriomin** [comment]
It should be happening already. Change the system language and Yalp should re-download the category list.

**Comment by marat1995** [comment]
@yeriomin а может добавить в Настройки Yalp смену языка?

**Comment by syl3nt** [comment]
Well.. I changed language to my native [PT] instead of English, and I don't get the translation, I still get the English list

**Comment by yeriomin** [comment]
@syl3nt The category list is redownloaded when you enter the app. This was introduced at the same time as all the other category features and has not changed since. I've checked on my devices and it works. If you change the system UI language, kill Yalp, launch Yalp again and the category names are not in your system UI language then its a bug.
