### ISSUE TITLE
[Feature Request] Download Apps within YalpStore or with an external Download Manager

### ISSUE THREAD

**Issue by moodl** [yeriomin/YalpStore#174]
When using a VPN App like DNS66 I can't download Apps anymore. It would be nice if Yalp Store would download everything on its own (like Firefox) or use an external Download Manager (ES File Explorer etc.).

[(Motorola Surnia 4G XT1524, Slim Rom 7.1.2 0.24 Beta; Issue occures on other devices as well)
(Even though this is somehow not your Problem a fallback solution for such problems would be appreciated)
(Downloading through a proxy would also be nice)]

**Comment by yeriomin** [comment]
This appears to be an [Android Nougat bug](https://issuetracker.google.com/issues/37105245). Turning on **any** VPN might break DownloadManager on Nougat, downloads start but do not progress. There is also an [DNS66 issue](https://github.com/julian-klode/dns66/issues/31) concerning this.

There already **is** a fallback in Yalp Store which activates when DownloadManager is missing or turned off for some reason. So as a workaround you can disable DownloadManager (Settings -> Apps -> Show System -> Download Manager -> Disable). Or you can whitelist DownloadManager in DNS66.

I do not have this problem on my devices, so I cannot check. Please tell me if it works.

I would not like to ditch DownloadManager, because it actually has a lot of functionality: download list, continuing download on reconnection, nice UI with progress and so on. It would require a lot of coding with new bugs and no functionality added to redo it fully in Yalp.

**Comment by yeriomin** [comment]
When Yalp detects it is running on Nougat and the VPN is on, it is going to use the fallback downloader from now on.
