### ISSUE TITLE
Update through FDroid not working if installed with OTA zip

### ISSUE THREAD

**Issue by Sirove** [yeriomin/YalpStore#178]
FDroid had the same issue back then when they first released the OTA zip but now you can update FDroid and the privileged extension casually through FDroid itself. 

That would save a lot of time especially because Yalp will probably release updates frequently.

![screenshot](https://cloud.githubusercontent.com/assets/24733228/26543497/79c49b54-445e-11e7-919f-c1510f0b7db1.png)

**Comment by yeriomin** [comment]
Right now the ota zips are being built automatically by travis-ci on every tag. Naturally, it does not sign the apk with the same key as F-Droid.

Looks like I will have to do it manually from now on.

You can do it manually too:

    gradle :app:generateOtaZipStable

This pulls the apk for current version code from F-Droid and puts it into the zip instead of the one built locally.

**Comment by yeriomin** [comment]
Updated the zip on the releases page too.

**Comment by techge** [comment]
Am I wrong or did you stop to do this the last releases? I totally understand if this is annoying to do every release, but OTA file would be much more useful if the f-droid signed apk is in there. I don't mind inserting the signed apk *myself* to update via f-droid in future (it has to be done only once), but I was wondering if there is a way to ensure, that every release on github builds the right OTA zip? This would help new users a lot, I guess.

I like to recommend tech innocent people YalpStore (after explaining the pros and cons of course), but they can not enjoy the full usefulness, unless the OTA zip contains the f-droid signed apk, I am afraid.

**Comment by yeriomin** [comment]
@techge 
> Am I wrong or did you stop to do this the last releases?

Yes. The last version for which I did that was 0.24. Since that time there were several problems with f-droid (month-long delays for different reasons) which made me set up travis-ci to build apk and ota zip as soon as I make a new release. Automatically building an ota zip for f-droid would be tricky because you never know when they actually build the new version. Sometimes in a day, sometimes in a month.

> This would help new users a lot, I guess.
> I like to recommend tech innocent people YalpStore

I would not call people who know what ota zip is "tech innocent" ;)

> I was wondering if there is a way to ensure, that every release on github builds the right OTA zip?

I wonder if it is possible to make f-droid build it... I'll ask them.

**Comment by ale5000-git** [comment]
@yeriomin: I'm not connected with F-Droid but I know it is possible.
You have to create a "separate app" for the OTA zip like for F-Droid Privileged Extension there are these two:
- https://f-droid.org/en/packages/org.fdroid.fdroid.privileged/
- https://f-droid.org/en/packages/org.fdroid.fdroid.privileged.ota/

**Comment by LuccoJ** [comment]
Another theoretical possibility is managing to make Yalp Store builds [reproducible](https://f-droid.org/en/docs/Reproducible_Builds/), at which point F-Droid could just use your own signature for their packages, and the clash would disappear. Things aren't always as ideal as to allow this in practice, but I'm just saying.

**Comment by ale5000-git** [comment]
My suggestion is to do both things, make builds reproducible and add ota app on F-Droid.
