### ISSUE TITLE
Can't login into Yalp Store with Yalp account and my account

### ISSUE THREAD

**Issue by piiiggg** [yeriomin/YalpStore#183]
I can't login into Yalp Store using both of my main Google account and Yalp account
### Info about your device
Xiaomi Redmi 3s, Android 6.0.1

**Comment by JonnyTech** [comment]
Have you ever logged into the Play Store with the Google app using those accounts? Can you try before any further troubleshooting. Which version of YalpStore?

**Comment by piiiggg** [comment]
I have, I'm using latest Yalp Store from F-Droid. Sometime the login working but sometime not with both account from Yalp and mine

**Comment by JonnyTech** [comment]
Are you using a proxy or vpn? Can you provide a logcat?

**Comment by yeriomin** [comment]
To log in using a built-in account I'm using a small service hosted on a free hosting. Looks like google is randomly denying logins from there due to too many login attempts. I will probably deploy more token dispensers. Somewhere.

Just try a couple of times more, it will log in eventually.

Failure to log in using your own account is strange. Would like to see the logcat.

**Comment by marat1995** [comment]
@piiiggg +1
Solution: Try to login.
I tried 3 times and could.
Mb I have  bad English.

**Comment by piiiggg** [comment]
@yeriomin I don't know how to get logcat from an app ?
Btw, this is how I login. Because the built-in account from Yalp can't download Spotify so I use my account
US account : failed => My main account : failed => Yalp account : worked => US account : failed => My main account : worked => US account : worked

**Comment by kaneru** [comment]
@piiiggg I've just had the same problem on my Xiaomi Redmi Note 3 Pro. What I did is reinstalling Yalp Store. Now I am able to login into Yalp Store.

**Comment by syl3nt** [comment]
What's happening? I'm always able to login on first attempt, with any account ..

**Comment by yeriomin** [comment]
@syl3nt Google randomly denies login requests. It is happening to me too.

Looks worrying. This is happening regardless of ip address or account (at least to all *my* accounts in all places I can try from). It's been happening for a couple of weeks. They might be changing the login process.  I'm now studying the current login process.

**Comment by marat1995** [comment]
@piiiggg kind of fixed this problem.
look here: 
github.com/yeriomin/play-store-api

**Comment by piiiggg** [comment]
Great, thanks everyone for confirm and fix it !

**Comment by Michi-BS** [comment]
Hi, I'm using yalp store already for a few months and I consider it the Number ONE app for keeping as far as possible from Google. I was using the built in yalp account for more privacy. So far so good.
Last week I needed to install a paid app which is linked to my gmail account. After installing my paid app I logged out from yalp store (latest version 0.26).
Now I'd like to install a new free app, but cannot login through yalp store anymore. Neither through the Yalp account nor through my own account anymore. On the latter I was prompted once by a Yalp dialogue that a two factor authentication is choosen  for this account (this is not true) and that I should setup the credentials for this. Of course I did not, as I don't want it.
A popup message says "Network error: git.hub.yeriomin.playstoreapi.GooglePlayExeption Error Server error".
So I hope someone can give me a hint how to get Yalp working again.

**Comment by yeriomin** [comment]
@Michi-BS This was fixed in 0.27. See the [releases page](https://github.com/yeriomin/YalpStore/releases).

**Comment by Michi-BS** [comment]
Thank you! Im going to wait until f-droid update comes and will give feedback then.

**Comment by Michi-BS** [comment]
Hi, I have found a probable cause for the behaviour decribed 3 days ago. I have logged in to the Ggle account which contains my payd apps. As this account already had contact with my various phones (old ones that I use to play araound with :-), some even mutiple due to the various mods I had tested. 
So I got rid of most of the entries in the "Find your phone" section by clicking on "Sign out from your phone".
After that action I entered the credentials of my account again in Yalp store of the phone that stalled recenty and the login succeeded i.e. I had access to my paid apps again. Of course this phone appeared again in the "Find your phone" section but this time anonymous i.e. the model name does not appear anymore. Instead it shows only "Android".
