### ISSUE TITLE
Fuction to force English for the Yalp GUI only

### ISSUE THREAD

**Issue by Sirove** [yeriomin/YalpStore#185]
The german translation is pretty good but not really clear enough:

Example:
installation: Installation
download: Installation

...so a function to force English for the Yalp GUI only would be nice.

**Comment by yeriomin** [comment]
If you can, please visit Yalp's [poeditor page](https://poeditor.com/join/project/LUPUijv2Cs) and fix this. It shouldn't take you more than five minutes, poeditor's ui is quite clear.

I'm reluctant to add new options/settings in general. And the language one in particular, because System UI language should be enough. Implementing it would leave Yalp with a redundant option and a broken translation. Why not fix the translation instead?
