### ISSUE TITLE
Download gets queued but never starts

### ISSUE THREAD

**Issue by subiol** [yeriomin/YalpStore#19]
When I try to download an apk by pressing Download button of an app in the YalpStore, the Android Download Manager opens and queues the apk download, but it remains queued forever. It never starts downloading the file. I tried waiting for almost 1 hour (and I have a very good internet connection) and the download never started, it remained queued.

I am using Cyanogenmod 13.

**Comment by Micha-Btz** [comment]
this problem i also had. the solution was to move the download directory out of the way and let the system create a new one. a permission problem.

**Comment by yeriomin** [comment]
Is there a way to 100% reproduce this? I have a cm13 device, but it doesn't happen.

**Comment by Micha-Btz** [comment]
@yeriomin just change the permission for the download folder. i have experimented with ssh and have botched something :-)

**Comment by subiol** [comment]
@yeriomin I am running Cyanogenmod 13 too. I do not know what logs or test are needed for you to check what's happening. Ask what you need and I will try to provide it.

**Comment by MSe1969** [comment]
Hi subiol, yeriomin, 
I had the same issue when I started using yalp store and was able to solve it. In my case, the following was the root cause:
I use afwall and a custom script to block access to the Google IP range. Obviously, with exceptions for e.g. Yalp store, and initially I forgot to also allow the android download manager to access Google. That has lead to exactly the behavior described in this issue. After allowing download manager to access Google, all worked fine. Could that be the reason also here?
Regards, mse1969

**Comment by subiol** [comment]
@MSe1969 that was exactly the issue. Adding the Android Download Manager to the apps allowed to access the network solved the issue. Thanks for the tip.

Since nobody else has reported the same issue, Ill close it.

**Comment by yeriomin** [comment]
Two people is a lot for a small app with one dev. Reproduced it! Thanks for detailed explanation, @MSe1969. I'll add more error reporting so it won't fail *silently*.
