### ISSUE TITLE
APK 0.16

### ISSUE THREAD

**Issue by schnatterer** [yeriomin/YalpStore#191]
### Expected behaviour
APK for version 0.16 available for download on GitHub and/or F-Droid

### Actual behaviour
No APK available on [GitHub Page](https://github.com/yeriomin/YalpStore/releases/tag/0.16), nor [buddybuild](https://dashboard.buddybuild.com/public/apps/592ec4685d513d00010e12a7/build/5935e588343e300001a0c871) nor [F-Droid](https://f-droid.org/repository/browse/?fdfilter=yalp&fdid=com.github.yeriomin.yalpstore) as of 2017-06-11

**Comment by marat1995** [comment]
+1

**Comment by AlfaOmega33** [comment]
+1

**Comment by yeriomin** [comment]
I've created [this f-droid issue](https://gitlab.com/fdroid/fdroiddata/issues/753). Bump it or add a comment there.

If I start uploading my own builds again the users will start emailing me about how Yalp does not get updates from f-droid due to signature mismatch. So I won't.

There is no (free) continuous integration system which makes build artifacts publicly available. But you *can* get them from circle-ci with a little trick. You can browse the build list [here](https://circleci.com/gh/yeriomin/YalpStore). Click a build and add `#artifacts` to the url after the page loads. You will get the list of artifacts even if you are not logged in. Like [this](https://circleci.com/gh/yeriomin/YalpStore/18#artifacts). Please don't upload these builds anywhere (especially 4pda). I will have to stop the circle-ci builds if the users start emailing me about signature mismatches.

**Comment by schnatterer** [comment]
Thanks for creating the issues at fdroid. I'm aware that they run their own built, using different keys for signing and and resulting in a certain time delay. So far, I've used the apks provided on your GitHub site, either flashed the ota.zip or extracted and installed the apk inside the zip. Why are you no longer providing those? It's not that uncommon to provide signed APKs via GitHub, e.g. [k9](https://github.com/k9mail/k-9/releases) also does it.

As for circle-ci, I followed your instructions but found only the unsigned apk, which cannot be installed. Can I find a signed APK somewhere?

APK 0.16 is now also available via fdroid, but 0.17 is not, yet. Will fdroid be the only source for signed APKs of YalpStore in the future?

**Comment by Laicure** [comment]
Me too, tried [that one](https://github.com/yeriomin/YalpStore/issues/191#issuecomment-307665437) above but it produces an unsigned apk that can't be installed.
The only way, I think, to have a signed apk is to use the _Android Studio_ which is not installed on my machine. I, then, relied on the [OTAv0.15](https://github.com/yeriomin/YalpStore/releases/tag/v0.15) :(

Yalp Store is the most reliable Google Play Store alternative that I've encountered so I'm all bets on this repo. ;)
