### ISSUE TITLE
please add yalp-store-0.18-ota.zip

### ISSUE THREAD

**Issue by bungabunga** [yeriomin/YalpStore#209]
it's not possible to background update apps with f-droid installed instance of yalp store.

thanks

**Comment by yeriomin** [comment]
Its possible if you have root. If you try to set installation method to "Using system permissions", Yalp will check for root and ask if you want to make Yalp a system app.

F-droid updates should not fail because the apk in the ota zip is taken from f-droid, so the signatures are the same.

I've updated the zip too.
