### ISSUE TITLE
Can't download app

### ISSUE THREAD

**Issue by marat1995** [yeriomin/YalpStore#224]
### Expected behaviour
Должна была отобразиться и скачаться прога Tiny Archers
### Actual behaviour
В результате поиска Yalp не нашел прогу.
Ее нашел Google Play.
Скопировал ссылку на приложение, Yalp нашел прогу по подписи пакета
(com.OsOs.TinyArchers)
Нажимаю скачать. Не качает. Предлагает только вручную.
### Steps to reproduce
1. В поиске Yalp набрать Tiny archers.
2.Убедитесь, что проги нет. Набрать com.OsOs.TinyArchers и открыть страницу приложения.
3.Убедитесь, что прогу нельзя скачать.

### Info about your device
SM T531, 5.0.2, Yalp 0.18, страна в поиске - Россия

**Comment by marat1995** [comment]
Еще в ручной загрузке сказано, что Play Store говорит, что приложение несовместимо с моим устройством. Мне Play Store дал скачать Tiny archers=>это баг Yalp.
Ошибка в тексте: последняя строка
не показывает НИКАКГО(о пропустил).

**Comment by marmeladema** [comment]
Hi and thank you for Yalp !

I do not speak russian, but i can't download any apps at least since 0.18. I tried clearing cache etc.. But i does not help.

Any suggestions ?

**Comment by yeriomin** [comment]
This should be fixed with the new compatibility checks.

@marat1995 Please speak English (I know you can) - you are confusing people. Also "Can't download app" is a misleading issue name.

@marmeladema This seems quite broad. Describe your problem more specifically, please. You can send me a bug report by tapping on developer's email on the About page (your logs and device info will be attached to the letter automatically).

**Comment by marat1995** [comment]
@yeriomin thanks a lot
