### ISSUE TITLE
unable to find/install some apps on some devices

### ISSUE THREAD

**Issue by ebbi2017** [yeriomin/YalpStore#232]
### Expected behaviour
Find "ScummVM" on all devices.

### Actual behaviour
On some devices "ScummVM" doesn't show up in the list to be ready to install.

### Steps to reproduce
0. Didn't use google account in yalp, using standard device settings.
1. Searched for "scu" on i9100, i9300, grouper.
2. the 1st suggestion is "scummvm" on all 3 devices, clicked on it, showing all apps to install.
3a. on i9300 "ScummVM" shows up, on i9100 and grouper it doesn't show up, but the downloaded apk transferred to other devices and installed is working. The i9300 is the only one with no gapps/google play installed. Other 2 devices where it cannot be picked and installed in yalp have play store installed.
3b. using another device setting f.e. google pixel it shows up on all 3 devices.

### Info about your device
i9100, i9300 with actual Lineage OS 14.1 Android 7.1.2; grouper with unofficial Lineage OS 14.1 Android 7.1.2.

**Comment by yeriomin** [comment]
This should be fixed already in 0.19. Issues #213 #224 #226 are similar.

Please try version 0.19 when it f-droid compiles it in a couple of days.

**Comment by yeriomin** [comment]
Apps can be considered incompatible with your device if it uses an outdated version of google apps. If you choose to spoof a different device, google apps version submitted with this device is used, not yours. This might explain the difference.

If you have google services on your device, Yalp uses your google services version code which lets you see all the apps visible through Play Store on that device. Yalp uses a predefined google apps version code on devices with no google apps. If you turn off device spoofing and still see different apps in Play and Yalp its a problem - message me.

Again, this should have been fixed in 0.19. So I'm closing this.
