### ISSUE TITLE
Security concerns about Yalp store

### ISSUE THREAD

**Issue by bungabunga** [yeriomin/YalpStore#240]
before using Yalp Store i was using Google Play Store but i only loged into it manualy about once a week, updated the apps and then loged out again. the reason behind this attitude was that i don't want to be constantly loged in to a service behind an app that has root access to my device so it can do nearly anything Google wants on it, anytime (and it's even not open source).

however, this wasn't an ideal solution and Yalp Store came as a far better one.

but i would like to know how close to Google Play Store Yalp Store stands (when using system priviliges) regarding these concerns:

1. can Google install/uninstall apps by their will or do whatever it wants on my device when i am logged into Yalp Store, 
a.) via my own Google account, or
b.) via Yalp's own Google account(s)?

2. can Yalp's own Google account(s) owner(s) install/uninstall apps by their will or do whatever they want on my device when i am logged in to Yalp Store via Yalp's own Google account(s)?

sorry, i'm not a developer so i can't check for these answers myself by looking into Yalp's code.

i think these are important security concerns that should be explained to people on Yalp's F-Droid page and on the main Yalp's Github page.

thanks for all your work!

**Comment by theo546** [comment]
1. Yalp cannot install app by their own or do anything on your device.
(Google Play Service maybe can, who know, it's not open source)

2. When you give your account info to Yalp, it's only to login on Google Play to download apps, because you need a token to download apps.
And no, the Yalp account cant get your phone to download (malicious?) apps.

**Comment by bungabunga** [comment]
i asked this because if you're loged in to Google account the official way you can also install apps from desktop web browser. so it seemd naturaly that you could maybe do the same by being loged in the Yalp way and if this is done via Yalp's own Google account then Yalp (or someone that hack into their accounts) could do it.

**Comment by yeriomin** [comment]
Hello.

1. a) No b) No
2. No

All of your concerns are linked to one Play Store feature: Play Store app periodically pings Play Store servers and if you choose to install something from a Play Store web site, Play Store servers will answer to those pings with a list of apps Play Store app needs to install.

I did not implement this in Yalp Store because I consider this feature useless at best (and intrusive at worst).

> sorry, i'm not a developer so i can't check for these answers myself by looking into Yalp's code.

There is nothing to be sorry about. But that means you have to *trust* me, and you have no reason to...

> should be explained to people on Yalp's F-Droid page and on the main Yalp's Github page.

The readme is too long already. I guess it is time to start a wiki.

**Comment by bungabunga** [comment]
> There is nothing to be sorry about. But that means you have to trust me, and you have no reason to...
i am well aware of that. let's say that i accepted this risk when i installed the app. i'm not really so much worried about the backdoors (it would be bizzare to put backdoor in an app that has source openly published and the binary is compiled by indipendent, trusted side). i worried more about the quality of code and possible security flows. but since this app is very much needed and i hope many people will install it, there will also be interest from people with knowledge sooner or later to inspect the code,

> The readme is too long already. I guess it is time to start a wiki.
that would be great and much desired for an app like this.

thanks again for doing something that many people want/need.
