### ISSUE TITLE
FR: Sorting

### ISSUE THREAD

**Issue by gerroon** [yeriomin/YalpStore#253]
Hi

It would be nice if it is possible to sort apps based on last update date, release date, ratings, naming etc when searching or looking for updated apps.

thanks

**Comment by yeriomin** [comment]
Hello.

Unfortunately, it is impossible.

To sort something you need to have the whole list of that something. Google Play Store does not have a way to request the whole list of all apps and there is no way to request a pre-sorted list.

**Comment by gerroon** [comment]
Hi


I understand that but you do get the list though initially (since yu display it). At least the sorting can work on first "20" once certain number of elements are downloaded to display or whatever important number is.

**Comment by Rikk** [comment]
@yeriomin If you store in the memory the items received from the query, you could easily manipulate them before displaying the list to the user. Incremental results add to the initial list and sort again. Why not?
At least for limited lists (eg. list of apps of one developer); dunno the performance for infinite lists.

**Comment by yeriomin** [comment]
@Rikk because as the list loads items would jump. It would be impossible to keep track with your eyes.

**Comment by gerroon** [comment]
Well, you do not have to sort while loading. Sorting can be done after the list is loaded by a  menu item "sort by date" The iuer can keep the default listing or click on sort by date.

**Comment by yeriomin** [comment]
@gerroon If I saw a filter button I would expect it to give me presorted lists. And since the search list is endless, the loading and rearranging would have to happen at several random times. At some point the beginning of the list would be sorted and the end - not. It is a really bad idea.

**Comment by gerroon** [comment]
How is the list is endless? I think there is a confusion. I originally menat sorting for "Updates" and then if possible for searches. 

Would not you want to see which apps are updates most recently? I have some apps updated like 2 years ago but because they start with a b c they always show up at the top.

**Comment by yeriomin** [comment]
> I think there is a confusion. I originally menat sorting for "Updates" and then if possible for searches.

I was answering to @Rikk.

> Would not you want to see which apps are updates most recently?

No. Every app needs to updated, does it not? The update date/age do not influence your decision to install the update... do they? And since the update list should be short and the only thing to be done is to "update all", I don't see a reason to add a special button just for the update list.

**Comment by gerroon** [comment]
Update frequency and update date affect my update/uninstall decision. Older and unupdated apps are regularly deleted from my phone but to see that I need to see if it has been updated recently or frequently.

**Comment by gerroon** [comment]
Also not every app does not need to be updated especially if an app goes from free to paid for instance or new version add some new cynical features.

**Comment by Rikk** [comment]
I also think it would be very helpful to sort by update time. I don't update all apps, especially those releasing versions with changes that make me angry. But sorting by date allows to see easily which apps received an update...
@yeriomin 
I see the Updates list is retrieved at once, so I think you could add sorting options for it.
My desire is to sort the list of Google apps by last update date.
I don't see how the start and the end of the list would differ, if you rebuild and sort the entire list at once, and only at predictable times (after each 'page' is retrieved?).

**Comment by yeriomin** [comment]
@gerroon 
> Older and unupdated apps are regularly deleted from my phone

I'm pretty sure that's a rare use case.

> if an app goes from free to paid for instance or new version add some new cynical features.

This is definitely a blacklist use case. Those apps won't get free again.

@Rikk 
> I see the Updates list is retrieved at once, so I think you could add sorting options for it.

Yes. Finite lists like update list or local app list can be sorted. There is another smaller concern there: update date is returned as a localized string (not a timestamp), so I will not be able to fully test the sorting mechanism for all languages.

> if you rebuild and sort the entire list at once, and only at predictable times (after each 'page' is retrieved?

No. Just imagine. You have 20 apps in the list of which 5 are visible. You load the next page. It contains random apps. Some apps will have to be inserted into the invisible area. This makes other apps jump. Some apps will have to be inserted right between the visible apps.

Since you guys insist, I will try to implement this at some point. But this is not going to be done soon because:

* There is no place for it in the current UI.
* It will be hard to make the update date sorting stable.
* In *my* opinion it is redundant.

**Comment by Rikk** [comment]
Thanks, thinking about is a good start :)

>Yes. Finite lists like update list or local app list can be sorted. There is another smaller concern there: update date is returned as a localized string (not a timestamp), so I will not be able to fully test the sorting mechanism for all languages.

By 'timestamp' do you mean 'seconds since Epoch'? Don't you have function to convert it? In JavaScript we have some ways, below is one:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
