### ISSUE TITLE
Download manager check bug

### ISSUE THREAD

**Issue by avently** [yeriomin/YalpStore#258]
I'm using Android 7.1.2. Everytime I'm downloading an app Yalp use in-app downloader ignoring the system one. 
And here you are making the wrong check:
https://github.com/yeriomin/YalpStore/blob/477ee2653f5cd1d300f90b4b8e8ba84eff817279/app/src/main/java/com/github/yeriomin/yalpstore/NetworkState.java#L25

This is why. First command was executed with disabled VPN. Second command was executed with Openvpn enabled. 
```
ls -1 /sys/class/net
ccmni0
ccmni1
ccmni2
ifb0
ifb1
ip6tnl0
lo
p2p0
sit0
tunl0
wlan0


ls -1 /sys/class/net
ccmni0
ccmni1
ccmni2
ifb0
ifb1
ip6tnl0
lo
p2p0
sit0
tun0
tunl0
wlan0
```
As you can see I have tun and tunl interfaces. Your code checks only "startswith tun". That's why everytime app thinks I use VPN.

**Comment by yeriomin** [comment]
Yep, since I've added ACCESS_NETWORK_STATE permission, this check can be replaced with a more android-like check on lollipop and newer. On older androids it will stay, it is good enough. 

For the record, though, what device are you using? Which android flavor? Maybe you have WiFi tethering on? What VPN solution are you using? Where does `tunl0` come from? The current network interface name check works on all devices I have, so you probably have something non-standard. Please send me a bug report through the Yalp UI.

**Comment by avently** [comment]
@yeriomin i use standard lineage os 14.1, Android 7.1.2. I don't have any specific settings like tethering. Maybe tunl0 comes from dnscrypt, I don't know. For VPN I use open source OpenVPN for Android app.
