### ISSUE TITLE
How is SafetyNet handled if at all?

### ISSUE THREAD

**Issue by Wandang** [yeriomin/YalpStore#263]
This is just a question.

How does Yalp handle SafetyNet? AFAIK this is a check from google (not sure if client or serverside) if the device is not modified and therefore prevents some apps from being installable.

Does the API used by Yalp have this check optionally for now? Does Yalp just pretend to be a specific agent/device?

Would you say that Yelp in the long run might be prohibited from installing certain apps because of it?

I wanted to switch from google play store to Yalp to get rid of everything in connection with google (I use LineageOS on a rooted OnePlus One and did install gapps because F-Droid wasn't enough for me).

/edit: Little extra question. I assume that any app depending on google play gaming services would no longer work/safe the game state? Not a big deal for me, only playing one game occasionally. 

Thanks for this project and taking the time to respond :)

**Comment by yeriomin** [comment]
> How does Yalp handle SafetyNet?

It doesn't.

> Does the API used by Yalp have this check optionally for now?

From [android docs](https://developer.android.com/training/safetynet/index.html):

> SafetyNet provides a set of services and APIs that help protect your app against security threats, including device tampering, bad URLs, potentially harmful apps, and fake users.

So SafetyNet checks are not done by the app which downloads apks (like Play or Yalp Store). Every app developer can add SafetyNet checks if he wants to check if the device is suitable (in developer's opinion) to run his app. You can install Pokemon GO through Yalp Store and it will or will not work depending on your android flavor and features. The SafetyNet check will happen **inside** Pokemon GO. Maybe the Play Store app also does the SafetyNet checks, but considering that apks can be taken from the device and uploaded anywhere, these checks would not be able to protect apps from being installed on "unsafe" devices. So these checks have to be done inside each app.

Check out [this list of stuff SafetyNet checks for](https://developer.android.com/training/safetynet/attestation.html#possible-results).

> Would you say that Yelp in the long run might be prohibited from installing certain apps because of it?

Not because of SafetyNet. It is impossible to directly distinguish Yalp Store from Play Store, so they can not *target* Yalp. But they might simply change the protocol and Yalp will stop working. It has happened before.

> I assume that any app depending on google play gaming services would no longer work/safe the game state?

Yes. Most apps will simply ask you to install gaming services. Some will not work, others will work but won't be able to save stuff. Worst case scenario: the game crashes during the gaming services check.
