### ISSUE TITLE
Fragment activity

### ISSUE THREAD

**Issue by nagayev** [yeriomin/YalpStore#269]
Plz add a fragment activities instead of activities because it's more conveniently.
I know fragment activities don't supported on Android 2.0 and lower, but
you can set min activity in AndroidManifest.xml to 11(Android 3.1+)
Now more than 99% of all android devices use Android 3.0+ and if you do it Yalp's users
won't suffer.

**Comment by nagayev** [comment]
Android usage statics(russian language):
http://blog.price.ua/news/opublikovana-statistika-android-2017-nougat-rastet-no-staryie-versii-poka-populyarnee/

**Comment by yeriomin** [comment]
> it's more convenient

For whom?

> Now more than 99% of all android devices use Android 3.0+

That's irrelevant.

> Yalp's users won't suffer

They will. Since all the Play Store API interaction is happening in a separate library, most Yalp Store code is UI-related, so it will have to be rewritten. Whatever you do, new code **always** comes with bugs.

To reiterate:

1. Implementing this gives **nothing** good to the end user. And that's the perfect scenario. Realistically, this gives a lot of bugs too. And this would require another half a year to implement and test. Guess who would have to do all that useless work?
2. I started building Yalp Store to support old devices. I'm happy with my HTC Desire with gingerbread. It can do 90% if the stuff new phones can. Creating a Play Store clone for as many people as possible was not my goal. There is no problem with running gapps on newer devices with gigabytes of ram. And if you hate being tracked or hate Google for a different reason, you can still use Yalp Store.

Sorry, that's a badly written issue. Main point: this change is not what user will see or even care about.

Here is a well-known template for a [user story](https://en.wikipedia.org/wiki/User_story): **As a [role], I want to [action] so that [benefits]**
