### ISSUE TITLE
automatically add f-droid installed apps to the blacklist (different approach)

### ISSUE THREAD

**Issue by CorePoint** [yeriomin/YalpStore#285]
Hey,

i know similar issues have been opened about this subject, but i have an idea that would't need a detection mechanism.
It would require collaboration with the F-Droid people though.
F-Droid could write wich apps it has installed into a file/database and YalpStore could read it and add them to the blacklist.
Would you be interested in adding this approach? If yes i would contact the F-Droid developers and ask them if they are interested to add this function too.

Greetings and thank you for your great work!

**Comment by yeriomin** [comment]
Hello.

Thank you for your kind words.

This has been asked several times already (#39, #69...), but unfortunately there is no way to reliably implement this. Collaboration with F-Droid will not help either, because of how Android works.

The source of the package *can* be saved in the system on app installation, but most likely is not. F-Droid did their part already, but for F-Droid to put itself as the application source, it has to be installed with the privileged extension.

Another way to know the application's source is checking its signature, but it can be checked only after the apk is downloaded. [This](https://gitlab.com/fdroid/fdroidserver/issues/291) looks promising, but it is not implemented yet and concerns only apps signed by the developers, not the apps built by f-droid.

**Comment by CorePoint** [comment]
Hey,

maybe i unterstood you wrong, but my idea would be to just write to a file stored on the user acessible media storage where every app with storage permission can read/write.
So F-Droid could write to that file and YalpStore could read it.
It's not a very novel/elegant solution for sure.
I don't want to get on your nerves with this, just want to understand which techinal limitations come in the way of this approach.

**Comment by yeriomin** [comment]
Well that would technically work.

But for such a small feature it requires too much effort. Collaboration between two unrelated projects is not easy and requires an independent standard or some other kind of bureaucracy.

Also architecturally it is a bad decision. Because it tries to work around OS limitations. Off the top of my head: it will be impossible to backup or delete with the app, because it belongs to neither. It won't work for older versions of the respective apps. It effectively becomes another non-reliable source of information. Just like the "application source" property of the android package manager. I'm sure F-Droid devs will not implement this approach.

**Comment by CorePoint** [comment]
Ok, thank you for the explenation, i appreciate it. :)
