### ISSUE TITLE
in-app billing permission

### ISSUE THREAD

**Issue by AlfaOmega33** [yeriomin/YalpStore#288]
Hi. Is possible add in-app billing permission for buy apps or make a donations, in order to completely replace the Play Store?? Of course, only for personal account and not for the one with Yalp Store credentials

**Comment by yeriomin** [comment]
Hello.

In short: impossible. See [README](https://github.com/yeriomin/YalpStore#faq).

If by some miracle and after a considerable waste of money I replicate the whole purchase process, it will not make a difference in a long run, because Google can and will change it, rendering Yalp useless and even harmful potentially.

Sorry.
