### ISSUE TITLE
APK Download

### ISSUE THREAD

**Issue by ghost** [yeriomin/YalpStore#289]
Please provide an APK file for download with every new release.
There is neither an in-app update from 0.25 to 0.26 nor any update on F-Droid available.

**Comment by zelleb** [comment]
0.25 is on F-Droid, 0.26 is gonna be there sooner or later, just wait.

**Comment by johanw666** [comment]
F-Droid is horribly slow, and since 0.25 doesn't work anymore this can be serious trouble. You can get an installable zip from mega:#!9QJB3KSb!TaAQ8EHRMLB0UiVQoDh6Q5gFEBBZlm1LuX2zkrExAWU . If you extract the apk from it you can not upgrade the current version because it is signed with my key (unless you run something like Xinstaller).

**Comment by yeriomin** [comment]
@johanw666 

> horribly slow

A week is not that much.

> 0.25 doesn't work anymore

What do you mean? It should work (not for paid apps though).

I used to publish apks for a couple of releases and it caused chaos. Since I'm obviously not signing my apks with f-droid signature, the installation over an existing Yalp Store will fail. People don't read. Not the README. Not even what their device is telling them. So I have to explain why it won't install and what a signature is. People who both cannot build from source and cannot wait for f-droid to build it are relatively not numerous.

Maybe it is time to try again.

**Comment by johanw666** [comment]
> A week is not that much.

It is if it does not work anymore or works only half. I have some paid apps which I ordered by an old device used only for Google Play.

I flash the installable zipfile anyway with TWRP, that procedure ignores signatures.

**Comment by JonnyTech** [comment]
https://f-droid.org/repo/com.github.yeriomin.yalpstore_26.apk

**Comment by yeriomin** [comment]
@johanw666 See the [releases page](https://github.com/yeriomin/YalpStore/releases)
