### ISSUE TITLE
"Error receiving or processing data occurred ad the HTTP level"

### ISSUE THREAD

**Issue by plumps** [yeriomin/YalpStore#290]
version: 0.25 (f-droid)

Hi, 

I'm on the latest CopperheadOS (Android Oreo based) version, which struggles with downloading ind installing the apps. It worked on the older Nougat based Images though. At first I thought it me be related to the new permission UI, which lacked the "Install unknown apps" bit, unfortunately it still seems to run into this downloading timeout.

**Comment by yeriomin** [comment]
Hello.

The error you are getting is pretty rare. Maybe the DownloadManager in CopperheadOS is not stable enough yet? Please reproduce it send me a bug report through Yalp ui with your name or the issue number so that I would know its about this problem.

Possible workarounds:

1. Did you try clearing Yalp data to force it to re-login and regenerate google device id?
2. You can force Yalp to use the fallback download manager like this: Settings -> Apps -> Show system -> Download Manager -> Disable.

**Comment by setuidroot** [comment]
Upgrade to version 0.26... fixed the DL issue for me (Remix OS 7.1.2)

**Comment by yeriomin** [comment]
@setuidroot 0.26 fixed paid app updates, not this, unfortunately.

**Comment by yeriomin** [comment]
It has been two months. This seems like an isolated case. I'm closing this, but if it happens again, feel free to open another issue.

**Comment by zeekoe** [comment]
Thanks for the hint! Similar here, disabling Blokada ("VPN" ad blocker) made it work for me.
