### ISSUE TITLE
Library of my apps

### ISSUE THREAD

**Issue by nagayev** [yeriomin/YalpStore#291]
Plz add a menu with information about library of my apps.
Of course only for using with not Yalp account.

**Comment by setuidroot** [comment]
Under settings, go to "Update Page" untick "Show only updatable apps" and tick "show system apps."  This will show all your apps in Yalp's main screen... otherwise go to settings-apps.  I don't mean to sound rude; I'm trying to help with the settings option... but I also am not sure if your trying to request an extra feature to the UI?  If so, maybe contribute yourself... it's open source.

I'm just saying; this is the best app ever, let the dev work on stuff that really matters.  Again just my opinion here, not being mean intentionally.

**Comment by nagayev** [comment]
@yeriomin yes, you understand me right.

**Comment by nagayev** [comment]
@yeriomin I think alot of Yalp users consider this feature important

**Comment by JonnyTech** [comment]
Not for me - if I want to see my previously installed apps, I can browse to http://play.google.com/apps - keep Yalp simple with the single purpose of installing apps only.

**Comment by yeriomin** [comment]
It has been two months. I still think this will not be useful and the users seem to agree. So I am closing this.

**Comment by nagayev** [comment]
@yeriomin okey,you are right
