### ISSUE TITLE
Beta downloads with built-in account

### ISSUE THREAD

**Issue by Limero** [yeriomin/YalpStore#294]
Ability to join application betas without using your own account should be added.

Ways this could be done:
* **Switch between stable/beta before downloading app.** I don't know if it's possible to quickly switch to beta, download the app and go back to stable and how this would affect other people using the same account. I also don't know how Yalp's version checking works, if it's possible to keep track of updates for both stable and beta simultaneously with one account.

* **Have two built-in accounts, one for stable releases and one that joins betas.** When users enable beta for the app in Yalp, the beta account will be used for downloading and updating the app whilst every other, non-beta app will be handled by the stable account.

**Comment by nagayev** [comment]
@Limero I think it isn't possible

**Comment by yeriomin** [comment]
Beta downloads is not the most important functionality of Yalp Store. Implementing this would add considerable complexity for the sake of mostly unused functionality. Sorry.

> I don't know if it's possible to quickly switch to beta

No, after the enrollment request, the enrollment status is unknown. One has to request app details until the enrollment status changes. Same thing with unenrollment.

> Have two built-in accounts, one for stable releases and one that joins betas.

Since different people will want different betas and built-in accounts are ordinary accounts, shared by everybody, this will never work well for everyone. Someone will be getting betas he doesn't want.
