### ISSUE TITLE
Option to download full apk instead of delta. delta fails in case of signature mismatch.

### ISSUE THREAD

**Issue by mavink** [yeriomin/YalpStore#295]
Can you please provide an option to download full apk instead of the delta apk? .

On official miui ROMs chrome and android-system-web-view apps are signed by mi/xiaomi rather than Google. This results in a mangled/corrupt/unparseable apk when the delta is combined with the old apk by yalpstore to generate the new apk.

Google play store is able to work around these signature mismatches. But if you don't want play store on your device then the only options are root and backup app data and uninstall and install new apk and restore app data. One can't use xposed installeropt to disable signature verification during installation and force install ignoring mismatched signatures. This option is not possible because a corrupt apk is generated due to combining of delta and apk with different signatures.

**Comment by yeriomin** [comment]
I see.

Could you reproduce this and send me a bug report through Yalp UI with your name and/or this issue number? I'm interested in the logs specifically. I might be able to detect this situation instead of letting the user decide.

Options are not such a great thing. Every option makes me support two behaviors instead of one, and forces user make decisions about things he might not know about. In my opinion Yalp Store has too many options already. Dealing with problems like this automatically would be ideal.

If no other solution can be found, I will add this option.
