### ISSUE TITLE
user interface regression in latest version

### ISSUE THREAD

**Issue by Larx** [yeriomin/YalpStore#301]
As I understand it, the change in the UI was thought to be an inprovement.
However, the current UI seems to be a disimprovement. With the old UI, the first list always showed me the the apps which could be updated. This is the most relevant information IMHO.
In the new UI, I first see a list of all installed apps, without any further information. This is kind of useless. Only a further click shows, if any, and if yes which, apps have updates available.
The old UI seems better to me.

**Comment by yeriomin** [comment]
No, it wasn't supposed to be an *UI* improvement. It was a *support* improvement, a refactoring. For months more features has been added and eventually there was too much logic on that screen. Half of the preferences affected it somehow. 

Also, as you said, it is a matter of opinion. There were issues/emails asking me to do the polar opposite of what you are asking ("I don't want updates", "Updates are slow", "I don't want to login, just want to see my apps"). There is no clear advantage of one way over the other, the user can do the same things, just the number of taps changes.  And I didn't make the change because it didn't matter much. But making the code easier to support is a good enough reason.

**Comment by Larx** [comment]
Other than the code support, which I cannot judge, I don't get any of the arguments against the old and in favour of the new way of doing things?!? If seeing all apps I have installed (without the slightest further information...) is the main reason for having a playstore replacement, I don't get it...

**Comment by yeriomin** [comment]
@Larx Since Yalp Store can delete system apps and convert normal apps into system apps and back, people might use it as a replacement for the built-in android app list. Maybe.

> without the slightest further information

What information should be there in your opinion?

**Comment by Larx** [comment]
Maybe version (installed and/or available), installed via PlayStore, system or normal app, and so on. I won't know, I use your PlayStore replacement app in order to install and update apps from the PlayStore, which seems to be an atypical use case (note: ;-) ). For me the obvious start page would contain the version/update info for the installed apps.
BTW, thanks for the app. This complaint is really a minor one...

**Comment by yeriomin** [comment]
@Larx 

> installed version

Can be done.

> installed via PlayStore

There is no reliable way to know where the package comes from.

> system or normal app

Its there already.

**Comment by Larx** [comment]
Alternatively, something like "installed version", "version available on PlayStore" or "not available on PlayStore" or something like that.
