### ISSUE TITLE
Feature: option to ignore mismatched signatures

### ISSUE THREAD

**Issue by Schekolda** [yeriomin/YalpStore#303]
### Expected behaviour
It would be nice to have an option to ignore signature mismatch. For example, it would be useful if you replace f-droid apps with google play ones

**Comment by yeriomin** [comment]
It would either be a security flaw (if your device ignores the signatures) or would cause confusion because attempting to install an update with a different signature causes android to say "Installation failed" without explaining the reason.

Note, f-droid does exactly the same when encounters a signature mismatch. The message was copied from f-droid source.
