### ISSUE TITLE
Make it harder to accidentally hit "update all"

### ISSUE THREAD

**Issue by rgh36167** [yeriomin/YalpStore#310]
Starting Yalp I see a list of apps with an "Check for updates" button bellow. After hitting this button I get a list of updatable apps with an "Update all" in exactly the same place.

So if UI lags it is very easy to hit the "update all" by accident. - and quite a bit of work to cancel all the downloads afterwards.

Perhaps this button could be moved to top, another place or ask for a confirmation?

**Comment by yeriomin** [comment]
> Perhaps this button could be moved to top, another place or ask for a confirmation?

Deliberately making UI inconsistent is a bad idea.

Please be careful. The button label changes and there is a transition between activities (unless you turned it off in device developer settings). Its hard to miss unless you are tapping the same spot without looking.

If anything, the "Check for updates" button should be removed. Navigation is not something that should be done with a button, [it should be done through a menu](https://material.io/guidelines/patterns/navigation.html). I left it there because checking for updates was happening on this screen before.
