### ISSUE TITLE
Crash and reboot loop

### ISSUE THREAD

**Issue by qouoq** [yeriomin/YalpStore#316]
Looks like the newest version of Yalp Store published on F-Droid is running into the exact same problem as the one below, encountered by DAVdroid on update 1.9.1, immediate system crash on installation, then reboot loop unless deactivating the app through recovery:
https://forums.bitfire.at/topic/1603/replicant-lineage-1-9-1-causing-instant-crash-and-bootloops

Yalp Store version breaking my system: 0.29
Version 0.28 working fine if reinstalling after recovery.

CyanogenMod 12.1, Android 5.1.1, F-Droid 1.0.1

**Comment by karcherm** [comment]
Same here, unofficial cyanogenmod 12.1 for GT-i9001 (ariesve, Samsung Galaxy S+) by Christopher83 from XDA-Developers. The boot intent handler causes memory corruption in system_server.

**Comment by forkoz** [comment]
Just bootlooped my 4.4.4 carbon. I guess no more trusting updates to yalp store from yalp store without reading changelog.

**Comment by yeriomin** [comment]
The issue mentioned by @karcherm is fixed in new build tools, so here is an apk built with 27.0.1.
[com.github.yeriomin.yalpstore_29_buildtools_27.0.1.apk.zip](https://github.com/yeriomin/YalpStore/files/1457963/com.github.yeriomin.yalpstore_29_buildtools_27.0.1.apk.zip)

@forkoz Sorry about your situation. But I am one dev with three and a half phones. This happened on none of them. I cannot check for everything, especially the things I don't write. Also, nothing in the changelog could tell you this would happen.

**Comment by forkoz** [comment]
This new APK works on my phone. I have recovery so I was able to recover but lost a few settings... ie frozen apps unfroze, receivers became enabled, etc.

**Comment by HennesTheSecond** [comment]
Ran into the same problems (with Yalp AND DAVdroid) on several LineageOS 13.0 devices. Downgrades (DAVdroid to 1.9 and Yalp to 0.28) solved the issue for me - but took nearly my whole saturday to find the trigger for this boot loops. :-/
Thanks a lot for your quick response, yeriomin! I understand that's not your fault. Would you please tag the fixed version so that it is pulled to F-Droid asap? Or delete 0.29 from F-Droid like the DAVdroid guys did with their v.1.9.1! Every day more and more android devices fall into boot loops otherwise. :-D

**Comment by qouoq** [comment]
Since the latest version fixes the issue, I assume it's better to close it, update on F-Droid is another topic.
