### ISSUE TITLE
[v0.29] Unable to get root > "Device not rooted"

### ISSUE THREAD

**Issue by MartinX3** [yeriomin/YalpStore#317]
### Expected behaviour
App should ask for root permissions after set the app to root.

### Actual behaviour
App is telling me, that my phone is not rooted.

### Steps to reproduce
1. Upgrade from v0.28 to v0.29
2. Activate Root (was on system rights before)
3. Profit

### Info about your device
Nexus 6 with MicroG for LineageOS 14.1 05.11.2017

PS:
I already removed the appdata and tried it again.

**Comment by Primokorn** [comment]
How did you root your ROM?

**Comment by JonnyTech** [comment]
Have you granted root permission to Yalp? Set root for "Apps" in "Developer Options" then go to "Manage Root Accesses" and check if Yalp is listed and enabled there.

**Comment by MartinX3** [comment]
Yeahr, I already did it.
It asked the permissions in the last version.
Now it ignored the allowed permission.
I removed the permission (set it back to 'ask')
But it doesn't ask

**Comment by JonnyTech** [comment]
Did you copy to `/system/priv/app/` or elsewhere? Is apk set to `chmod 664`? Are you sure that it is not installed in two different folders?

**Comment by MartinX3** [comment]
I only used the in-app option to make this app a system app in v0.28
But after the upgrade to 0.29 i removed this app via the uninstaller and installed it fresh again from f-droid.
Maybe it is still where the app copied itself in the system partition?

**Comment by yeriomin** [comment]
>I only used the in-app option to make this app a system app in v0.28

This option copies Yalp Store apk to `/system/priv/app/`.

Every system app in android is updated by putting a new apk **into the usual non-privileged place with all the other apps**, while leaving the system apk in `/system/priv/app/`.

>But I removed the app by the deinstallation routine of android....

This routine does not remove anything from `/system/priv/app/`.

So you probably left Yalp Store apk somewhere. This should help:

1. Remove it using the *deinstallation routine of android*.
2. Then go to `/system/priv/app/` and remove it from there.
3. Reboot.

Yalp Store can remove itself, but since you've been poking around, I cannot guarantee it will work. Do it manually to be sure.

**Comment by JonnyTech** [comment]
> This option copies Yalp Store apk to `/system/priv/app/`.

That should read `/system/priv-app/` (note the dash)

**Comment by MartinX3** [comment]
Yes, @JonnyTech is right.

@yeriomin Thank you for the advice.
After a ROM-Update, this app wasn't a systemapp anymore.
And was again able to get root.
I will now let this app be in the root mode and won't activate the system mode anymore.
I don't want to get this weird bug again, that dissallowed me switching back from the "system app"-mode. :)
