### ISSUE TITLE
Add Multi-select option for update list

### ISSUE THREAD

**Issue by rancidfrog** [yeriomin/YalpStore#336]
After searching for updates, there is only option to `update all` via button and select app one-by-one to update some apps only.

Adding option to multi-select apps could be useful, when there is many apps but not all wanted for update.
1 option ha e check-box to select which apps to update, and button changes from `update all` to update selected apps.
Another way is to add option for `select` on long-press which takes you to selection mode:
For example, fx file explorer
Select,
![](https://s17.postimg.org/u05ywmnof/Screenshot_20171201-141557_01_01.png)
Selection mode where you can select more apps to add,
![](https://s17.postimg.org/fgytv9zpb/Screenshot_20171201-141615_01.png)
Here again, `update select apps` would appear

**Comment by yeriomin** [comment]
I don't think adding such fine tuning is a good idea.

* There is a blacklist option in the long-press menu already.
* There is a download option in the long-press menu. If you don't want to update everything, "long press -> download" is not slower than "long press -> select -> update selected".
* Unlike a file manager, there is no reason for Yalp Store update list to be accessed more frequently than once every couple of days.

**Comment by yeriomin** [comment]
I'm closing this, sorry. No discussion is happening, the users did not support this and as it is, the usefulness/difficulty ratio of this issue is too low in my opinion.

**Comment by 2SI3NX** [comment]
@yeriomin The "ignore updates" for each app will not be effective when say.. half the user's apps are coming from F-Droid and he does not want to completely ignore updates in yalp store incase some apps in F-Droid are too late in being released or take a very long time to be released..especially if there is a security update that is urgent, the user would then rather go to Yalp store and quickly update the app.  So it would be good for the user to keep tabs on the F-Droid apps and "Un-select them" in an attempt to update the rest.

The user would want to know what apps are in need of an update even if those apps are downloaded from F-Droid.

Im sure having a check-box option for multi-select shouldnt be that much of a big mission, is it? i hope not..  Because this would actually be useful for some users. Not everyone "just uses one store to update"

Please re-consider for this to be integrated.

**Comment by yeriomin** [comment]
@2SI3NX 
> half the user's apps are coming from F-Droid

Even after you describe it, I don't see why that is necessary. Non-play-store apps are most likely not updatable without user interaction due to signature mismatches. Pressing "update all" will not update them. "Update all" updates all apps it can. Why would you NOT update an app which is updatable? If you don't want some new feature or change, just blacklist it. And for that you would need to enter the app details page to see the changelog.

> having a check-box option for multi-select shouldnt be that much of a big mission

Well no task is too big given enough time. Considering that Yalp should work on a great variety of devices, I think debugging it would take time.

I have most of my apps from f-droid and I'm not even using blacklists in Yalp. I press "update all" and non-f-droid apps are updated. The rest I update through f-droid.
