### ISSUE TITLE
Error "...signed with a different key"

### ISSUE THREAD

**Issue by duttyend** [yeriomin/YalpStore#339]
Dear Sergey,

First of all, thank you so much for your amazing app !!!

I was using the 0.30 version on a new HTC (android 7.0, stock, no root) and couldn't update the majority of the included apps.

After downloading the file, and clicking on "Install", it returned "This application is signed with a different key... You must first uninstall the existing application...".

I couldn't uninstall the existing apps because they show as "system app".

In Yalp Store, I went to Settings -> Updates -> unticked "Delta updates" and it solved the problem !!! I could update every app that was previously failing !

I thought it could be useful to report this as other people might be in the same situation.

### Expected behaviour
Application update process should succeed

### Actual behaviour
Application update process returns error "...signed with a different key"

Thanks again and have a great day!

**Comment by rugk** [comment]
Usually the error message means, it has been installed by a different application/via a different source/different APK. As you say it is a system app this is very strange.
YalpStore just uses the official APKs from Google Play, so there should be no difference. Also the delta updates should not cause it.
Or maybe there is a problem with these?

**Comment by duttyend** [comment]
Yes, I know, but the phone was brand new, I literally just took it out of the sealed box and installed Yalp Store from the github release apk, downloaded with stock browser.

As you say, the issue is very strange but I can assure you this was the only way to get the apps to update... I had been pulling my hair for a few hours, repeating the process over and over (I initially thought the apk were corrupted from a bad WiFi connection) but finally I was so happy to find this "solution" !!!

**Comment by yeriomin** [comment]
Hello!

I'm glad you find Yalp Store useful.

Thank you for your observation. Your case is rare but not unique. Some vendors put modified apks of popular apps on their devices. Play Store app is "magic", so it can detect it and replace them in background.

This means delta updates might need to be turned off by default...

**Comment by FrankEular** [comment]
Sorry for my ignorance. I suffer from a similar issue for a user app: Firefox (57.0.4 to 58.0.1). I installed Firefox from a third-party app store (say, A.apk), and today it failed to update it in Yalp with an error "...signed with a different key"). I upgraded Firefox to 58.0.1 from a third-party (to, say, B.apk). It succeeded to install, from which I deduce that A.apk and B.apk have the same signed key. Later I saw this post, and use Yalp to download the Play Store version mannually (say, C.apk) that it succeeded to install.

From this It seems to me that A.apk, B.apk and C.apk share the same signed key. I think that the first error about the key conflicts is also due to Delta updates. Is it reasonable?

**Comment by yeriomin** [comment]
@FrankEular Every app has its own signature. Most likely, same apps from different sources have different signatures. It is not a rule, but it is likely. It depends on the developer's decision.

Android will not let you update the app if the signatures don't match, no matter delta update or not.

I can not know about the specific apps.

Did I answer your question?

**Comment by FrankEular** [comment]
What happened is that, Android (LineageOS 14.1) allowed me to update to the same version downloaded by Yalp (without removing the previous installation), but the first trial to update with Yalp failed. I don't know what leads to this, but I don't know what happens if a version that I've installed was ignored in Play Store (that's to say, for example, I installed version 2, but Play Store has version 1 and 3), and then I do a delta update from Yalp (in my example, update to version 3)?

**Comment by yeriomin** [comment]
@FrankEular If the question is "Can delta updates cause an update error?", the answer is "Maybe". I've never encountered it personally, but the users are saying it happens. That's why it is no longer default.

To say anything specific I would need all those apks you tried.

**Comment by jpellegrini** [comment]
I just wanted to confirm that delta updates did cause that error on my system also (I use OmniROM on a Xiaomi Redmi Note 4).

I did turn delta updates off, deleted the package updates that were downloaded from` /storage/emulated/0/Download`, opened Yalp Store again, and everything worked.

Perhaps it would be helpful to have a warning in the description of the "delta updates" option?

**Comment by fungs** [comment]
Same here, disabling delta updates solved the problem. This is a stock android with regular play updates. This issue should not be closed.
