### ISSUE TITLE
account-less access

### ISSUE THREAD

**Issue by anarcat** [yeriomin/YalpStore#34]
hi,

while i find it amazing that we have an alternative to the google store, one of the primary reasons why I would need such an alternative is to download freely available software from the app store *without* requiring a google account, ie. "anonymously". i understand why tor support (#13) is not implemented at a technical level: google services often block tor or require captcha to be filled, so it makes that impractical. but other tools (e.g. [gplaycli](https://github.com/matlink/gplaycli)) work fine without registering a google account. granted, they may not implement the whole google play store API, but they do what i need. the only problem with gplaycli is that it doesn't run on the phone, so I don't actually use it anymore...

could this be considered as a functionality here?

**Comment by yeriomin** [comment]
Hello.

`gplaycli` uses the same way of accessing Google Play as my app, so it DOES use some credentials. See [this `gplaycli` issue](https://github.com/matlink/gplaycli/issues/38) for more info. And from security/anonymity point of view there is no difference between using a fake account registered by you and using a fake account registered by some other person. The account `gplaycli` uses might be blocked at any time, and I feel uncomfortable knowing that my app will stop working not because of *my* bug.

Also, using predefined credentials will force yalp to use one device id for all devices, which makes it possible to download apps your device does NOT support.

I understand that this would be convenient, and you are not the only person who asked for this, so I will implement this in some way. Thanks for writing an issue.

**Comment by anarcat** [comment]
hahaha wow, that's amazing. thanks so much for the reply, i didn't know gplaycli was being so... well, nasty.. ;) i think you are right - i just didn't know gplaycli was using a fake account, and i was assuming it was possible to navigate the app store without an account...

automatically generating gmail accounts could definitely be problematic. but maybe helping the user with initial registration could be a good idea...

**Comment by yeriomin** [comment]
Done. App uses a predefined account to access Play Store. Without sharing password with the world. If it stops working, it will happen because of some Google restriction. Probably.

**Comment by anarcat** [comment]
amazing, thanks so much!!!
