### ISSUE TITLE
Request: Clarity about apps installed via F-Droid? Ignore?

### ISSUE THREAD

**Issue by wolftune** [yeriomin/YalpStore#345]
It would be nice if I could set Yalp Store to ignore apps that came from F-Droid, not update them to the Google Play versions.

Incidentally, it's not clear to me as an end-user if there's anything altered about an app by coming from Google. Do they inject apps with some special proprietary Google something or is it the same version-wise as available outside of Google?

**Comment by TomJansen** [comment]
This is already being discussed here #343

**Comment by yeriomin** [comment]
@TomJansen is right.

It is impossible to reliably determine where the app comes from. Only after the apk is downloaded the signatures of installed apk and the downloaded apk can be compared.

> Incidentally, it's not clear to me as an end-user if there's anything altered about an app by coming from Google.

Impossible to know. Depends on the developer. Many apps on f-droid are not submitted there by developers and are compiled only because they have maintainers which remove proprietary components from the source.
