### ISSUE TITLE
Yalp doesn't download extra OBB data

### ISSUE THREAD

**Issue by japzone1** [yeriomin/YalpStore#350]
### Expected behaviour
Download app, both APK and OBB Data are downloaded.

### Actual behaviour
Only the APK are downloaded

### Steps to reproduce
Find any game that has extra OBB data and try to download it.

### Info about your device
ZTE Axon 7 Android 6.0.1

----
This problem means that I can download and install the APK of a game using Yalp, but the game will just crash on launch since it's missing GBs of data that are supposed to be in `/storage/emulated/0/Android/obb/app.name`

**Comment by yeriomin** [comment]
Downloading obbs has been supported for a long time. See #64.

Just tested it with com.gameloft.android.ANMP.GloftMOHM, obbs were downloaded properly.

Obbs are downloaded when download links are available. Sometimes they are absent. Some developers choose to host the obb files themselves instead of uploading it to Play Store. Android docs state that it is app developer's responsibility to check if the obb files are present during runtime and download them if needed. Check out https://developer.android.com/google/play/expansion-files.html for more info.

What app do you have trouble with? Please provide the package name.

**Comment by timofonic** [comment]
@japzone1 Oh, yes. It would be very nice to know what app is causing the issuue :)

**Comment by yeriomin** [comment]
@japzone1 Cannot reproduce. If this actually happens, please open a new issue with more info, specifically the app name.
