### ISSUE TITLE
/dev/null/Download ? ("Download diretcory could not be created or is not writeable")

### ISSUE THREAD

**Issue by saljut7** [yeriomin/YalpStore#353]
### Before creating an issue
1. Make sure you are running the latest version of Yalp Store. Check [here](https://f-droid.org/packages/com.github.yeriomin.yalpstore/).: `YalpStore version 0.32 (F-Droid)`
2. Search for similar issues [here](https://github.com/yeriomin/YalpStore/issues?q=is%3Aissue+is%3Aclosed). `/done`
3. Send developer a bug report using Yalp's built-in crash tool. Or go to Yalp's About page and tap on the developer's email. This creates a email with your device info and recent logs attached. `Will send a bug report with the issue number as subject`

### Expected behaviour
Using YalStore as second app source next to F-Droid I wanted to install one App only available via PlayStore. After providing my google credentials and choosing "download" I expected a download process.

### Actual behaviour
I got ""Download diretcory could not be created or is not writeable". Under Settings -> Download directory I have `/dev/null/Downloads` which I even can not change (just deleting "Download" is possible bot not setting a folder or a path).

### Info about your device
- Samsung Galaxy S2 gt-i9100
- Android 7.1.2 (LineageOS 14.1-2017-12-13-nightly-i9100)

**Comment by yeriomin** [comment]
The `/dev/null/` part comes from your OS ([getExternalStorageDirectory()](https://developer.android.com/reference/android/os/Environment.html#getExternalStorageDirectory())). Since its a nightly, it is not *very* surprising. WRITE_EXTERNAL_STORAGE permission lets Yalp Store put files into that "external storage", but your OS says the path to that storage is `/dev/null/`. Not much can be done here.

Also, check out #308.
