### ISSUE TITLE
Downloads stop receving data while downloading

### ISSUE THREAD

**Issue by dfkfahhdkfaslhfashdlfalshdfldshk** [yeriomin/YalpStore#358]
I have Sprint in the United States and Gapps is disabled in Samsung Galaxy S7 Android 7.0 November 1, 2017 security patch
Soemtimes when i try to download a app, it will download for a while and then without notification, it will still say downloading, but no no progress will be achieved. For example, if I try to download a 10 MB app, it might stop at 4.89 MB and the only way to fix it is to try again.

**Comment by yeriomin** [comment]
Yalp Store uses a system component to download files. If download has started, it is no longer "under jurisdiction of" Yalp Store. This problem is either with this component or your network connection. You can force Yalp Store to use the fallback download manager like this: Settings -> Apps -> Show system -> Download Manager -> Disable.

**Comment by TPS** [comment]
Any hope to internally optionally configure Yalpstore (via setting, I mean) to use fallback?

**Comment by yeriomin** [comment]
@TPS It is a bad idea for a couple of reasons:

1. Implementing a download manager from scratch requires a lot of coding. The existing fallback is very minimal, and letting users choose it will increase the number of problems, not decrease it.
2. The cause of this issue is either faulty android system component or faulty network connection (or a combination of both).
3. This issue is unique and issues similar to this are rare and each of them has a unique cause which makes it impossible to create a solution which works (with or without a user-configurable option).
