### ISSUE TITLE
Use F-Droid privileged extension to install apk

### ISSUE THREAD

**Issue by AMDG2** [yeriomin/YalpStore#364]
Hello !

Thank you for the great project ! I am wondering if it will be possible to use the F-Droid privileged extension to install APKs. This will allow easy update of Yalp Store through F-Droid itself because it won't be a system application. Also the only process that will run with high privileges will be the F-Droid privileged extension.

This feature will allow users to have easier install procedure without rooting the phone nor using an OTA package to update Yalp Store. For example I am using the LineageOS fork from [microG](https://lineage.microg.org/), it is shipping with the privileged extension and f-droid. For certain reasons I don't want to root my phone, and I also would like to avoid manual installation steps with Yalp Store and disable unkown sources apk install.

As far as I understand to achieve that goal we will need to add the Yalp Store into the authorized clients of the privileged extension here: https://gitlab.com/fdroid/privileged-extension/blob/master/app/src/main/java/org/fdroid/fdroid/privileged/ClientWhitelist.java.

This need to decide which signed version of Yalp Store will be authorized to use the privileged extension. Maybe the one from F-Droid is the right one.

On the Yalp Store side it seems to need a new Installer*Something*.java to support the F-Droid privileged extension installation method.

What do you think of this proposal ? Are you willing to develop and/or merge this feature ?

**Comment by AMDG2** [comment]
The F-Droid client PrivilegedInstaller can be used as a start point for developing the Installer for Yalp Store : https://gitlab.com/fdroid/fdroidclient/blob/master/app/src/main/java/org/fdroid/fdroid/installer/PrivilegedInstaller.java

**Comment by yeriomin** [comment]
Hello.

I'm glad you find Yalp Store useful.

When I was implementing privileged installation I used the F-Droid privileged extension as reference. I didn't completely copy it and didn't make Yalp Store compatible with the F-Droid extension because:

* I did not think Yalp Store would be added to that white list you mentioned.
* At that time the extension didn't even work with f-droid client on my device. (might have been my fault, I don't know)
* Considering the points mentioned above, I decided not to confuse the users with installing a yet another package/extension/whatever.

> This will allow easy update of Yalp Store through F-Droid itself because it won't be a system application.

System app update is not much different from ordinary app update. The original apk is kept in the system partition for signature checking only. The updated apk is placed in the ordinary user partition where all the other user apps are stored. The app runs from that updated apk in the user partition.

> to achieve that goal we will need to add the Yalp Store into the authorized clients of the privileged extension

Yes.

> Maybe the one from F-Droid is the right one.

I don't expect the f-droid devs to trust any other build.

> On the Yalp Store side it seems to need a new InstallerSomething.java

Yes. It would look almost exactly like the [PrivilegedInstaller](https://gitlab.com/fdroid/fdroidclient/blob/master/app/src/main/java/org/fdroid/fdroid/installer/PrivilegedInstaller.java) you mentioned. 

> What do you think of this proposal ?

It can be done... technically. I'm not sure if the f-droid devs would be willing to add Yalp Store to their white list. They seem to be swamped... Adding Yalp Store to that white list would require some kind of audit and I don't think they have time for it. Yalp Store is [rather big](https://codebeat.co/projects/github-com-yeriomin-yalpstore), not as big as [f-droid client](https://codebeat.co/projects/gitlab-com-yeriomin-fdroidclient-master), but still. Also, all Yalp Store builds on f-droid since October were greatly delayed for different reasons. Many other apps were affected and still are affected. Version 0.33 which I tagged on 23.12.17 is still not available on f-droid.

Another reason not to add Yalp Store to the white list is that would indirectly mean that f-droid trusts all the apps in Google Play Store.

Asking wouldn't hurt, I guess. I'll add an issue to https://gitlab.com/fdroid/privileged-extension/issues

**Comment by ale5000-git** [comment]
@yeriomin: I doubt as you that it can happen in this way but it would be nice if you fork the privileged extension to create one for you.
Maybe making it working in both ways, if there is the privileged extension installed use it, if there isn't and Yalp Store is a system app use it directly.

**Comment by yeriomin** [comment]
https://gitlab.com/fdroid/privileged-extension/merge_requests/25

**Comment by yeriomin** [comment]
The f-droid devs refused.

> I think the best way to manage this is for the Yalp Store developers to manage their own fork of this with the signing keys they need.  That fork can then set up its own OTA ZIP for flashing it that includes the Yalp APK.  That will really be minimal work.  I would then document how to add this one line for any ROM developers that want to support Yalp.
> 
> Here are some reasons why it does not make sense to include the Yalp keys here:
> 
> * F-Droid is fundamentally about free software and we only want to give the F-Droid mark of approval for things that do not promote proprietary software.  Google Play clearly does not fit into that.
> * it is hard enough to convince ROM developers to include the F-Droid signing key, having the Yalp key there will only make it harder.
> * we have no idea about the security practices of Yalp devs, etc.
> 
> I forgot to include: the custom Yalp fork should also change the applicationId so it is not org.fdroid.fdroid.privileged.  It should have an applicationId related to the Yalp one.  There is no problem having multiple copies of Privileged Extension installed.  If there is, that's a bug that should be fixed.

It is not a surprise and not a problem, I think. There are two options already for people who want background installation.

Since there is no way to reuse the preinstalled f-droid extension, there is no point in merging its support into Yalp Store master branch. But if anyone is interested, the extension support can be found in the [fdroid-privileged-extension branch](https://github.com/yeriomin/YalpStore/tree/fdroid-privileged-extension).

**Comment by AMDG2** [comment]
F-droid devs answer is clear and as you said not a surprise. Thank you for doing the extension support work, that is great !

It seems you doesn't want to follow the proposal of the F-droid devs to fork their privileged extension. Can you confirm that ?

Also if (one day) I come with a fork ready, usable and testable are you willing to merge the extension branch to Yalp Store master ?

**Comment by yeriomin** [comment]
>It seems you doesn't want to follow the proposal of the F-droid devs to fork their privileged extension. Can you confirm that ?

Yes. The goal of the extension is to let user install apps in the background. Yalp Store can do that already.

>Also if (one day) I come with a fork ready, usable and testable are you willing to merge the extension branch to Yalp Store master ?

Sure.

**Comment by yeriomin** [comment]
@ale5000-git Sorry, no. It is not a good idea to add code which depends on something as rare as an external component which has to be compiled separately.

If someone compiles the privileged extension, it should't be a problem for that person to compile Yalp Store from the [fdroid-privileged-extension branch](https://github.com/yeriomin/YalpStore/tree/fdroid-privileged-extension).

**Comment by benpye** [comment]
@yeriomin Is there any reason you didn't go forward and fork the F-Droid privileged extension and then merge the branch? It seems that keeping it in a branch will just result in it rotting...
