### ISSUE TITLE
Do you give support to "APK Expansion Files"?

### ISSUE THREAD

**Issue by msdos** [yeriomin/YalpStore#368]
Do you give support to https://developer.android.com/google/play/expansion-files.html? I'm trying to download https://play.google.com/store/apps/details?id=com.ndrive.oimapas, a message saying "downloaded extended apk" is shown but the app doesn't work after installed and I'm trying to see if it's related to the expansion part.

**Comment by yeriomin** [comment]
Yes. Downloading obbs has been supported for a long time. See #64.

I can not check your specific app, since it is geo-restricted, but other apps are downloaded with obbs.

Also, note the following:

> Most of the time, Google Play downloads and saves your expansion files at the same time it downloads the APK to the device. However, in some cases Google Play cannot download the expansion files or the user might have deleted previously downloaded expansion files. To handle these situations, your app must be able to download the files itself when the main activity starts, using a URL provided by Google Play.

Even if the obbs were NOT downloaded by Play Store (Yalp Store in your case), the app (com.ndrive.oimapas) must be able to download them itself.

This is not an issue. Please, use [gitter](https://gitter.im/YalpStore/Lobby) if you have any other questions.
