### ISSUE TITLE
Yalp Store with Play Store package name

### ISSUE THREAD

**Issue by mahesh1729** [yeriomin/YalpStore#378]
Now that BlankStore and FakeStore are not being updated, and YalpStore works well, it would be helpful if it had the same package name and signature (spoofing) of Google Play Store. It would be a good addition to MicroG apps for a Google free Android.

**Comment by ale5000-git** [comment]
I think FakeStore is updated, just more rarely.
It just that it does rarely need updates since it does't do anything.

My opinion is that it would make sense to do what you suggest since it will break F-Doid updates of Yalp Store and it will just over complicate things.

**Comment by yeriomin** [comment]
Funny enough, it appears that functionality of FakeStore and Yalp Store does not overlap.

I agree with @ale5000-git : they should be separate tools and there is no benefit in changing the package name.

> It would be a good addition to MicroG apps for a Google free Android.

See https://github.com/microg/Phonesky/issues/5

**Comment by mahesh1729** [comment]
Fair enough. FakeStore only fakes the presence of Google Play Store, nothing more. BlankStore fakes the presence of Google Play Store and also is able to download and install Apps. Yalp Store can only install apps.
I have used Blank Store and since moved to Yalp and Fdroid, using both a lot. What I was suggesting is a combination of FakeStore and Yalp, like a improved version of BlankStore.

**Comment by ale5000-git** [comment]
@mahesh1729: FakeStore free you from calling your market app like Google Play Store.
You can have also five (for example) different market at the same time; a thing that you cannot do if everyone is called with the same name.
Yalp Store work also if Google Play Store is installed, if you name it the same it wouldn't work.

**Comment by woj-tek** [comment]
OK, but with only Yalp Store, if an app performs startup licence check (happens sometimes) then it won't work (because FakeStore doesn't retrieve this information and YalpStore is… separate).

I was just thinking - would it be possible to expose an interface with state of the app (if we use our account) and purchase/licensing status, that FakeStore (or better yet https://github.com/microg/Phonesky/issues/5) could use to make the verification without actually reimplementing whole logic?
