### ISSUE TITLE
MX Player Pro not startable / Purchase History

### ISSUE THREAD

**Issue by fred0r** [yeriomin/YalpStore#395]
### Expected behaviour
MX Player Pro should start.

### Actual behaviour
MX Player Pro doesnt start: https://i.imgur.com/5Kvoxng.png

### Steps to reproduce
1. Buy MX Player Pro using Playstore
2. Install Yalp
3. Install MX Player Pro with Yalp
4. Start MX Player Pro

### Info about your device
Wileyfox Swift with 'native' microg-Lineage-image (14.1-20180212-microG-crackling)
Google Play Services are installed.

**Comment by fred0r** [comment]
Same with Poweramp+Unlocker.

**Comment by yeriomin** [comment]
@fred0r Yalp Store only downloads apks. It does not re-implement or emulate in-app purchases. I assume, Google Play Services are used to perform this failing check, but this depends on each specific app. Since you have both microg and Google Play Services, there might be a conflict. [This discussion](https://github.com/microg/android_packages_apps_GmsCore/issues/309) seems to be about something close to your problem.
