### ISSUE TITLE
Certificate issue when updating apps from Fdroid

### ISSUE THREAD

**Issue by flasheater** [yeriomin/YalpStore#41]
When updating apps that were previously installed using FDroid, the Package Installer fails with "App not installed".

This is due the fact, that the Apks from FDroid are signed with a different certificate.

The workaround is to manually uninstall the app first, then reinstall using Yalp. 

It should be possible for Yalp to detect this case and offer to reinstall automatically, because FDroid does that.

These apps can be used for testing because in my experience they have always had the more recent version in the Play Store as compared to FDroid:
- Telegram
- VLC

**Comment by yeriomin** [comment]
On installation the certificate check is not done by the Play Store app (or f-droid app), but by the android system. It is forbidden to install an app with one signature over an app with a different signature. Forcing you to uninstall prevents maliciously modified app packages from getting your data.

Play Store can overwrite apps installed from f-droid because it is a system app and because it thinks it is boss ^^.

It can be done with root, though I'm not sure it should be done.

See [here](https://developer.android.com/studio/publish/app-signing.html) for details.

Checking if the certificates match is possible after the apk is downloaded (certificate is stored inside). So warning the user instead of showing installation manager window with "App not installed" is possible.

**Comment by yeriomin** [comment]
Certificate checking and a warning added on attempt to install app from Play Store over an app from other source. Implemented in master.
