### ISSUE TITLE
Material design [Request]

### ISSUE THREAD

**Issue by SciFi1818** [yeriomin/YalpStore#439]
A rebuild of the ui to Material Design would be awesome...

**Comment by Rikk** [comment]
Download from XDA: https://labs.xda-developers.com/store/app/com.github.yeriomin.yalpstore
It is in test, not stable enough.

**Comment by SciFi1818** [comment]
Seems like work is going on...Cool..

**Comment by yeriomin** [comment]
@SciFi1818 @ale5000-git @Rikk @leopard20 

You can get a working prototype of a "material design" Yalp Store if you build the `contemporary` [flavor](https://developer.android.com/studio/build/build-variants#product-flavors). It has been there since 0.36. I've been reluctant to put it here or on f-droid because:

* a lot has changed *inside* so it is bound to be less stable
* not so much has changed *outside* so it is not very impressive. I've been trying to make Yalp Store "style-less" to make it have the default UI of the OS it runs on. So on devices with api>=21 it already conforms to the material design guidelines (except the drawer and the buttons mentioned below)
* minSdkVersion is 14 now because of the android support library dependency so it cannot replace the default `legacy` [flavor](https://developer.android.com/studio/build/build-variants#product-flavors)
* apk size has doubled

#### Changes
* [Navigation drawer](https://material.io/guidelines/patterns/navigation-drawer.html) instead of the [options menu](https://developer.android.com/guide/topics/ui/menus#options-menu)
* [FAB](https://material.io/guidelines/components/buttons-floating-action-button.html)s in lists where there is a definite "main thing to do" e.g. "update all"
* Details page - buttons no longer stick to the bottom.
* Details page - "page background" pic, like in Play Store, if provided by the app developer.
* Activity transitions between app lists and details.
* minSdkVersion is 14 now because of the android support library dependency
* since the style is enforced, it should look the same on all devices, so no holo ui on api<21

So the main change is the drawer. I tried to rip its sources from the support library like I did with [some other things](https://github.com/yeriomin/YalpStore/tree/master/app/src/legacy/java/android), but it is too tightly coupled to the rest, so I would have to rewrite a lot of it or include half of it. So I just included it as the dependency.

I'm planning to support both versions simultaneously so that newer devices would get the big "material design" version (if the device can run api>=14, it should not be a problem) and the old devices would get the small legacy version.

If you want to try it, you can:
* try the alpha version on xda labs. I've put it there because it is possible to clearly mark it as alpha (incomplete) there while the stable is available too.
* build it yourself - run Android Studio and choose `contemporary` in the build variants.
* get it here [com.github.yeriomin.yalpstore.plus_40.apk.zip](https://github.com/yeriomin/YalpStore/files/1977085/com.github.yeriomin.yalpstore.plus_40.apk.zip)

It is funny that this issue has appeared around the same time as #436 ...

**Comment by ale5000-git** [comment]
@yeriomin

[Here](https://stackoverflow.com/a/27932367/490687) explain how to make Material Design apps compatible with API 8.

Also there can be <uses-sdk tools:overrideLibrary=" "/> in AndroidManifest.xml to override minSdk of libraries.

Also there is [com.takisoft.fix:preference-v7](https://github.com/Gericop/Android-Support-Preference-V7-Fix) to fix problems of the official libray.

**Comment by yeriomin** [comment]
@ale5000-git 
> make Material Design apps compatible with API 8.

A bigger apk is not an issue for API 14 and up but might be an issue for API 8. And since API 5 has to be supported, it still wouldn't allow me to build just one version. The stackoverflow answer you linked is a bit old. The support library had different minsdk back then, so its not a trick, just an older support library.

> `<uses-sdk tools:overrideLibrary=" "/>`

This will make it build, and then crash... unless I test every feature on every device. This is very hacky.

> Also there is com.takisoft.fix:preference-v7 to fix problems of the official library.

com.android.support:preference-v7 is not used.

Thank you for your input, but unless I reimplement the drawer from scratch, the support library with its minsdk will have to stay. Or am I missing something?

**Comment by Rikk** [comment]
@yeriomin do you need some feedback about the Plus version?
- When opening Yalp from a Google Play link (direct link to an app), options menu is not available; going to other page and back will make it appear.
- Dark theme: menus have white background and white text, not readable.
- App title over cover image is often white on white or black on black.
- App cover image is displayed with wrong proportions, probably because the cover area is too tall; reducing the initial height of cover image would fit and look better.
- Think about the versionCode for supporting both versions. Let's say
40001 and 40002 where 40 = 0.40, 00 = build or minor version (0.40.0), 1=traditional 2=material
Maybe would want to add extra field for architecture in the future.
I like codes being the date, eg 2018050200

If you need screenshots I can post later, or if you are already aware of these things then okay.

**Comment by yeriomin** [comment]
>do you need some feedback about the Plus version?

Sure.

@Rikk 

>When opening Yalp from a Google Play link (direct link to an app)

You mean the launcher link? This means the installed apps page is displayed. It has no options menu, navigation moved to the drawer.

>App title over cover image

Either image or title should be displayed. Title fades in as you scroll bottom and hide the image. Are they displayed simultaneously?

>App cover image is displayed with wrong proportions

What are your screen proportions? What is your device?

> Think about the versionCode for supporting both versions.

Is it a question? `legacy` flavor has sequential version codes, nothing changed. `contemporary` flavor version code is `legacy` flavor version code plus 1000. See the [build script](https://github.com/yeriomin/YalpStore/blob/master/app/build.gradle).

**Comment by Rikk** [comment]
Posting gifs explaining these. I question the necessity of fading title before it materialize into the top bar...
![yalp cover issues](https://user-images.githubusercontent.com/2916485/39680916-575ffa8c-517c-11e8-8ff1-f971d633178e.gif)
Look at this sequence:
![missing menu](https://user-images.githubusercontent.com/2916485/39680918-5d05e1a4-517c-11e8-8200-a6b5278274cf.gif)
Images are at 100% of my screen (480x800).

**Comment by TPS** [comment]
[Galaxy](https://f-droid.org/app/in.dragons.galaxy) (source @ https://github.com/whyorean/Galaxy) is a fork that accomplishes this.

**Comment by yeriomin** [comment]
@ale5000-git 
> publish them on F-Droid with 2 different internal names

> Both should have update checks so putting them with different versions and same internal name could only confuse people and automatic update checks.

Their functionality will be identical, so I am planning to just build 2 apks with one package name. There will be no reason to use the legacy version for people with new devices, so they will automatically get the version with updated ui. I don't see a reason to make this an *explicit* choice.

Like here:
https://f-droid.org/en/packages/org.geometerplus.zlibrary.ui.android/

**Comment by Lonami** [comment]
I personally like the simple style of the application. It just works. And quoting [`README`'s FAQ](https://github.com/yeriomin/YalpStore#faq):

> Q: Why isn't Yalp Store using Material Design? Is it going to?
> A: No. The priority for Yalp Store is backwards compatibility and size. It works on every android since Android 2.0 Eclair. Implementing Material Design would require adding a heavy dependency and a lot of purely-UI code.

Just my two cents, the application is good :)

**Comment by Golbinex** [comment]
I dont see reson why we couldn't have material design because of 1% of old android users. Yalp store could be splitted into main app and legacy one for older devices.

**Comment by Lonami** [comment]
Having to maintain two applications is far from optimal or even desirable in my opinion… Even though it *could* work out easily with different builds, I guess. No idea how this works on F-Droid.

**Comment by yeriomin** [comment]
@Lonami Thanks! It won't change much. Like I said, the only noticeable incompatibility with the material design guidelines is/was the navigation drawer.

@Golbinex You didn't read the issue, did you? ;)

> I dont see reson why we couldn't have material design

You can have anything you want, but *I* think UI should not be a priority. And most of it is material-design-compliant anyway already.

> because of 1% of old android users.

Because I started Yalp Store as a client for old devices. New devices work just fine with gapps, old devices don't. Yalp Store being open source is a secondary benefit.

> Yalp store could be splitted into main app and legacy one for older devices.

See the discussion above. It is done already. Once enough feedback comes in to consider it stable, I'll add it to f-droid.

**Comment by ale5000-git** [comment]
@yeriomin
> Their functionality will be identical, so I am planning to just build 2 apks with one package name. There will be no reason to use the legacy version for people with new devices, so they will automatically get the version with updated ui. I don't see a reason to make this an explicit choice.

Can an user switch from one version to another and vice-versa without lost data?
If yes, then it will be good to have the same name.
I'm one of the rare users that mess continuously with the phone ;)

**Comment by Rikk** [comment]
>Can an user switch from one version to another and vice-versa without lost data?

Yes, but you need to use 'pm' in command-line or adb.

@yeriomin what do you need for debugging/fixing the title bar (black, white or dark) that overlaps the cover image?

**Comment by ale5000-git** [comment]
Android can downgrade while keep app data using `adb install -r -d <path-of-an-apk>`
I haven't yet tried but I hope it works.

**Comment by hodanli** [comment]
is there material version of 0.42.

**Comment by NitroNils** [comment]
I just saw a new app on f-droid which is a fork of Yalp with Material :) 
https://f-droid.org/app/com.dragons.aurora 

On June 18, 2018 5:22:56 PM GMT+02:00, notifications@github.com wrote: 
>is there material version of 0.42. 
> 
>-- 
>You are receiving this because you are subscribed to this thread. 
>Reply to this email directly or view it on GitHub: 
>https://github.com/yeriomin/YalpStore/issues/439#issuecomment-398092461 

-- 
Sent from my p≡p for Android.

**Comment by YiiKuoChong** [comment]
@NitroNils Too bad the creator haven't provided a OTA zip file. I saw the issue but wish he would do it periodically, I could though but not sure how

**Comment by anunaym14** [comment]
@TPS Just a heads-up.

**Comment by TPS** [comment]
@anunaym14 I'm unsure of what @whyorean's [doing w/ each repo, so I'm hoping for clarification](https://gitlab.com/AuroraOSS/AuroraStore/issues/8), before I fix my reference above.

**Comment by TPS** [comment]
@anunaym14 Fixed above, since @whyorean has [clarified](https://gitlab.com/AuroraOSS/AuroraStore/issues/8).

**Comment by yeriomin** [comment]
Contemporary flavor can now be found on the github releases page. Built by travis-ci with every release. Next step - f-droid (if there are not too many bug reports).

**Comment by Lonami** [comment]
Sad, so material design is gonna be the default. Oh well, projects move forward. Thankfully this is a one-time application I don't run daily.

**Comment by yeriomin** [comment]
Time to close this. Please open new issues if something is wrong with the contemporary version, but not the legacy one. Or if you have any suggestions concerning the new UI.

**Comment by kg1701** [comment]
I don't know? Personally I am lost 😐 sorry
