### ISSUE TITLE
Not available in my country apps

### ISSUE THREAD

**Issue by sinarahimpoor** [yeriomin/YalpStore#482]
How to download apps are not available in my county ? 
I was test an app and Yalp has crashed !!!

**Comment by ale5000-git** [comment]
The minimum info should be:
- Yalp Store version
- Name of the app that cause the crash
- Maybe also a logcat

The developer cannot read your mind ;)

**Comment by sinarahimpoor** [comment]
last version .42
app name 1010!

**Comment by sinarahimpoor** [comment]
at all can we download not available app from yalp?

**Comment by Mikaela** [comment]
I managed to download and install apps that are not available in my country by using a VPN and then opening Yalp Store.

**Comment by yeriomin** [comment]
There is no such feature in Yalp Store. I'll quote the [FAQ](https://github.com/yeriomin/YalpStore#faq):

> Q: Can Yalp Store download region-locked apps?
> 
> A: Not directly. But it is easier than with Play Store. Play Store servers detect your location by your ip address, so to appear to be in a different region you are going to need a VPN. Log out of Yalp Store (clearing Yalp Store app data does the same thing). Turn your VPN solution on and choose a desired location. Log in to Yalp Store again. You should be able to download apps from your chosen region now.

> Yalp has crashed !!!

This gives me nothing to work with. Reproduce the crash and use the built-in feedback tool.

> app name 1010!

Downloaded with no issues.

> at all can we download not available app from yalp?

I'm not sure I understand.

**Comment by dimqua** [comment]
Is it possible to use proxy instead of VPN?

**Comment by Rikk** [comment]
>Is it possible to use proxy instead of VPN?

Just fill it in the Settings.

**Comment by yeriomin** [comment]
@dimqua It does not matter. What matters is your ip address.

**Comment by ale5000-git** [comment]
@yeriomin: Once you get the final download link, can it be download from an IP of a "not allowed country" or the IP check is also there?

I have a thought of writing a PHP script (to be installed on a remote server) to "proxy"ing only some things (and use less data as possible on the server), if feasible.

**Comment by yeriomin** [comment]
@ale5000-git I haven't checked, but I'm pretty sure only API requests are checked for location. Download link should work from anywhere.

I thought about this too. Technically this will work, but practically... this solution would probably be unable to serve multiple users simultaneously due to google's rate limiting.

**Comment by ale5000-git** [comment]
If we could establish a sort of API with the minimum of requests needed to get the download link, then I could create an open source PHP app (maybe also with caching if possible).
Also a chain is possible if multiple servers with the same PHP app can interact when they hit rate limit.

To make it simple it would be nice to have an API where Yalp Store query the selected server (maybe under https, possibly also with digest authentication for private servers) with everything inside POST parameters and the server returning textual response (defined in the API).

**Comment by yeriomin** [comment]
@ale5000-git 

> with the minimum of requests needed to get the download link

There is https://github.com/yeriomin/play-store-api already. I've been lazy, so it doesn't have docs, but getting a download link is 1-2 calls if you use it. There is also https://github.com/yeriomin/token-dispenser which is a play-store-api wrapped with a REST API. Extending token-dispenser to have *search* and *download link* endpoints would be easy, but it makes little sense because of the rate limiting. There is little value in a server which can't serve more than 1-3 users simultaneously.

If you are interested, https://github.com/matlink/token-dispenser is a fork which adds a *device id* endpoint.

> To make it simple

This will work if you make it, but it is far from simple (meaning complex, not difficult) ;)

**Comment by ale5000-git** [comment]
I didn't mean in this way, but a new simple API where YalpStore query the server (that must be trusted and manualy set by the user) with a POST HTTP 1.1 query like https://custom_host_name/my_script_to_get_dl_link.php with post variables like token="12345" and app_name_to_dl="an_app" and then the server return this text for example D|https://google/download/url\r\n that must be parsed by YalpStore.

**Comment by ale5000-git** [comment]
If the token is relative to the builtin YalpStore account maybe the PHP script can cache the download link for 30 minutes (for example, I don't know the expire time of the Google servers links) and serve it to unlimited user that try to download the same app in the same time (if the same url can be downloaded multiple times simultaneously).

Alternatively the PHP script instead of serve links can download and store apps in its own cache and serve to YalpStore at the same time (the second time for the same app it just serve the cached file (this require more bandwith and space on the server).

It can aldo do both things togheter based on certain conditions.
