### ISSUE TITLE
When a new Beta Play Services version is released, often it's not displayed properly in YalpStore

### ISSUE THREAD

**Issue by Rikk** [yeriomin/YalpStore#488]
When a new Beta Play Services version is released, very often it is not displayed properly in YalpStore, ie, sometimes there is no update shown at Updates and app page shows older version but new Beta can be downloaded manually; other times, the new version appears with no release date like this:
![screenshot_2018-06-19](https://user-images.githubusercontent.com/2916485/41631881-7cfff2ca-740d-11e8-9831-673bc218406b.png)
It seems random when the update is shown with missing date and when it is not shown at all.

@yeriomin Please, I'd like to ask if you could investigate what's happening.
Thank you.

PS: please don't forget to publish material version updates. It rocks 😉

**Comment by yeriomin** [comment]
Note that during the update request this app is *never* returned.

I'm pretty sure this package is just "special". As far as I know, Play Store app doesn't even show its updates, just runs the update automatically as soon as it is available. So the devs probably don't bother with updating the app info properly. If update date or any other thing (notice the download count) is empty it is because google does not return it.

Also, I don't think it is a good idea to sign up for betas of this app even if you are prompted. How do you even know it is a beta?

>please don't forget to publish material version updates

I will. There was a regression in the previous tag and it is kinda cheating to publish a random commit. It would be hard to support. 0.43 will come out soon.

**Comment by Rikk** [comment]
>As far as I know, Play Store app doesn't even show its updates, just runs the update automatically as soon as it is available.

I don't think so. While I understand "Play Store" itself doesn't have an app's page and is auto-updated, I see Play Services does have a page and it shows updates for me; anyways, I'm almost always using on my phone a newer stable version than Play Store is showing.

Play Services updates are very confuse, for some accounts even with Beta Program enabled, Play Store won't show the real latest beta, but for some accounts it shows the latest and for others there may be an intermediate beta. I consider a version Stable when it shows for all or most accounts (today it is the 12.6.85); I can retrieve 12.8.xx versions only when Beta program is enabled.
I use Yalp to check for the latest version available, not meaning I'll use or recommend it. I've got 12.6.88 while it was a previous Beta, but it is on the same branch as stable (12.6.xx) and it is working normally for me.

**Comment by Rikk** [comment]
@yeriomin do you know if Google can lock users to see arbitrary versions, despite granting them access to download a version with higher number? I'm observing a situation where it displays 12.8.66 but I can manually get 12.8.69 — yes, Beta test is enabled:
![gms crazy versions](https://user-images.githubusercontent.com/2916485/42570293-d6e3c6f8-84e9-11e8-9e52-e2ac11316401.gif)
And I know some uploaders of apkmirror have access to 12.8.70 and .72 too...
