### ISSUE TITLE
Whitelist boxes in main menu have no effect

### ISSUE THREAD

**Issue by momo42** [yeriomin/YalpStore#490]
Ticking the whitelist box that comes down when you open the three dot menu on an installed app in main menu has no effect. When you close Yalp Store and start it again the previously ticked app is not on the whitelist. When you add the app via options / manage whitelist the whitelist entries are stored as expected.

I've seen this behavior on Yalp 0.42 but don't know when it started to go wrong. Strange thing is that on an other of my devices these whitelist checkboxes work as expected (also Yalp 0.42) Both devices LineageOS 14.1.

I'm using the app in german. So please excuse my wrong translation back to english. I think the problem is clear.

edit: I also recognized that when you tick an app via options / manage whitelist the main menu entry is not updated until Yalp Store is restarted. Perhaps this behavior connected to the error above.

**Comment by yeriomin** [comment]
Cannot reproduce.

But something similar does keep happening. #427 for example. From what I could piece together it seems like a display issue (the list is stored properly).

> When you close Yalp Store and start it again

Do you mean *force* close?

> until Yalp Store is restarted

 What do you mean by restart?

> main menu

You mean "Your apps" list?

**Comment by SebiderSushi** [comment]
I'm able to reproduce the issue in Yalp v0.45 both legacy and contemporary.
And i've found an additional interesting detail.

- From Installed App List (reproduces bug):
1. Clear Yalp Store App data in android Settings
2. Launch Yalp
3. From Installed App List add the first 5 apps to black/white list
4. Open the android recents screen and swipe to remove Yalp
5. Launch Yalp, **only the topmost App** shows to be on the black/white list
6. Open `/data/data/com.github.yeriomin.yalpstore/shared_prefs/com.github.yeriomin.yalpstore_preferences.xml` and check under `<set name="PREFERENCE_UPDATE_LIST">` -> **Contains only the first package name** instead of all 5

- From Preferences (works as expected):
1. Clear Yalp Store App data in android Settings
2. Launch Yalp
3. Open Settings > Change apps black/white list, tick the first 5 entries, click ok
4. Open the android recents screen and swipe to remove Yalp
5. Launch Yalp, the previously added Apps all show to be on the black/white list
4. Open `/data/data/com.github.yeriomin.yalpstore/shared_prefs/com.github.yeriomin.yalpstore_preferences.xml` and check under `<set name="PREFERENCE_UPDATE_LIST">` -> The corresponding package names are all included.

Summary:
The app has not been "force closed" in these scenarios. In both scenarios the app is being closed in the exact same way. Yet somehow only the Preference Activity is saving correctly, while the Installed App List Activity can't deal with more than one entry to the set PREFERENCE_UPDATE_LIST.
