### ISSUE TITLE
Yalp does not seem to list all updates

### ISSUE THREAD

**Issue by gerroon** [yeriomin/YalpStore#504]
Hi

I also started using Apkupdater (https://github.com/rumboalla/apkupdater). One thing that caught my attention is that Yalp list half the updates that Apkupdater finds. Apkupdater is using Gplay as the backend as well.

I am using Yalp's own user.

**Expected behavior**
I expect Yalp to find all updates

**Actual behavior**
It list some updates but not all 

**Steps to reproduce**
1.open yalp
2.update
3.compare the results to apkupdater's update list

**Your setup**
Device model, android falvor, Yalp Store version
Lineage Os 14.1, 0.43

**Comment by Rikk** [comment]
Possibly because it also show updates from other sources like APKMirror, which may include system apps which usually should not be updated with files taken from other devices.

**Comment by gerroon** [comment]
@Rikk 

No, I only have Google enabled. When it does pull from other sources, you have duplicated in Apkupdater clearly.

**Comment by Rikk** [comment]
- Not using device spoofing in YalpStore?
- Using same Google account in both apps?
- Official Play Store app lists same amount of updates?

**Comment by gerroon** [comment]
- I am not using device spoofing

- I am using the devs's accounts. I do not have Gplay account.

- I do not have Gplay on my device

**Comment by yeriomin** [comment]
@gerroon It is not unexpected and not an issue. For me Yalp Store gives *more* updates.

> I expect Yalp to find all updates

"All" is actually ambiguous and the definition of "all" is up to google. The decision which updates to expose is done on server side.

> I am using the devs's accounts.

Different accounts = different updates. Quote from [FAQ](https://github.com/yeriomin/YalpStore/blob/master/README.md#faq):

> For different reasons the app developer might choose not to release his app for all users at the same time. This is called a [staged rollout](https://support.google.com/googleplay/android-developer/answer/6346149?hl=en). Be patient, the update will come.

There are other possible reasons for the difference:

* apkupdater uses an old version of play-store-api library
* apparently, apkupdater requests details of every app individually, instead of using the update request
