### ISSUE TITLE
"ignore updates" gets forgotten, blacklist works 

### ISSUE THREAD

**Issue by lighhw68** [yeriomin/YalpStore#520]
Have most apps from f-droid and normally blacklist them from settings / change apps blacklist. This works.

Instead when setting "ignore updates" from updates list it does seemingly work,  the app even appears blacklisted in the blacklist if I look at it - but after 24 hours the notification comes and the app is again presented as updateable and the ignore / blacklist setting seems completely forgotten. Apps which were previously blacklisted with the other
method are still blacklisted however.

**Comment by Rikk** [comment]
I also have problem with the "Ignore this update" option, when I uncheck it and reopen the app page it appears checked again.

**Comment by red-black-bonsai** [comment]
I've got the same problem as lighhw68, though the time may occasionally be less than 24 hours.

Version 0.43 installed from yalp-store-ota-contemporary-43.zip

**Comment by yeriomin** [comment]
@Rikk Found and fixed in 0.44.

@lighhw68 @red-black-bonsai Have been trying to reproduce this for more than a month now. No luck. If you have any more specific steps to reproduce this or any other observation, please mention it. There have been similar issues before. I ended up blaming that on the implementation of SharedPreferences in certain ROMs.
