### ISSUE TITLE
[feature request] support shelter/workmode

### ISSUE THREAD

**Issue by nr458h** [yeriomin/YalpStore#531]
Hi there is app called [Shelter](https://github.com/PeterCxy/Shelter) which uses the android workmode to separate and freeze/unfreeze apps.

It would be great if I could choose in Yalp to install an app into the shelter and also keep the apps there up-to-date.

If this don't fit your aims (keeping the app as small as possible and simple) please feel free to close this  issue.

Thanks anyway for your time spend on this project

**Comment by 0lm** [comment]
this is already possible. you can copy yalpstore into the shelter. and the sheltered version of yalpstore will only check updates for sheltered apps, or install apps only into shelter.

**Comment by dimqua** [comment]
Idk about shelter (it doesn't work for me), but with Island you can clone the download manager into Work profile, so Yalp works.

**Comment by ghost** [comment]
There are two different reasons why I ask for this feature.
The first one: As I installed f_droid and yalp as a system app everything messed up, when I installed them in the shelter.(_EDIT I managed to get it work I had no problems with the download manager but for example there is only one icon for both main and shelter ... and some different things - but as mentioned later on this is not the main point_ )
**But the second is much more important to me, because, when I use yalp in the shelter I only can look for updates if i unfreeze all apps. This is really annoying if you have a lot of apps in your shelter.** 

It came to my mind there is also a third point:Not that big issue, but there are at the moment for example also the tor app I need to install twice.
So thats why. - because of the comments above I can understand if this feature is not implemented, but anyway of course it would be great

Thanks

**Comment by dimqua** [comment]
> when I use yalp in the shelter I only can look for updates if i unfreeze all apps.

Yes, but there is nothing Yalp can do with it. This feature should be imlemented in Shelter. And it has been implemented, AFAIK, new version is just not released yet.
