### ISSUE TITLE
>0.43 versions cannot be installed on android 8.1 devices with >512MB RAM

### ISSUE THREAD

**Issue by BuggyDriver** [yeriomin/YalpStore#546]
You can't install yalpstore >0.43 on android 8.1/ lineage OS 15.1 with f-droid, because you get "needs: android.hardware.ram.low".

**Comment by DJCrashdummy** [comment]
out of curiosity i tried to install yalp-store via f-droid on a SGS2 `i9100` (1GB RAM & Android 2.3) and it also refuses to install versions >0.43 because of `android.hardware.ram.low`.
although forcing the installation worked without any problems and yalp-store seems to run without any complains...

**Comment by ale5000-git** [comment]
@yeriomin: Isn't enough to set required to false?

**Comment by JonnyTech** [comment]
Manually downloading from https://f-droid.org/repo/com.github.yeriomin.yalpstore_45.apk worked when the F-droid client refused to install due to being "incompatible".

**Comment by tuxayo** [comment]
More info: https://github.com/yeriomin/YalpStore/issues/543#issuecomment-431344739

**Comment by DJCrashdummy** [comment]
f*** off stale-bot! this just provokes unnecessary and annoying messages (beside stale-bot itself) like _"+1"_, _"push"_ etc.

nonetheless this is still not fixed! ...at least the corresponding issue #543 is still open (for now).
