### ISSUE TITLE
Paid minecraft errors with "license error"

### ISSUE THREAD

**Issue by jedie** [yeriomin/YalpStore#588]
Minecraft was bought in the past. I have installed it successfully in the past and have been able to play it. But it was a different mobile phone and with lineageos and gapps.

The new phone is with eelo and microg and i used the same google play account in yalp store.

Can I install and play minecraft only with the real google play store?

**Comment by Mynacol** [comment]
Exactly. The license check is performed by the Google Play Store.

**Comment by jedie** [comment]
OK, so i must install the gapps, right?

Maybe it makes sense to create a list of apps that can't used via Yalp store?

**Comment by tomasz1986** [comment]
> OK, so i must install the gapps, right?

Not necessarily. You need only the Play Store apk, placed in the /system/priv-app folder.

**Comment by RLTYChq** [comment]
> > OK, so i must install the gapps, right?
> 
> Not necessarily. You need only the Play Store apk, placed in the /system/priv-app folder.

Sorry to bring up an older thread but I'm trying to get this working but still getting the license check error. If its not too much trouble could you give me a step by step on how to install through the system-priv method you mentioned? Thanks for any help you can offer.

**Comment by tomasz1986** [comment]
> Sorry to bring up an older thread but I'm trying to get this working but still getting the license check error. If its not too much trouble could you give me a step by step on how to install through the system-priv method you mentioned? Thanks for any help you can offer.

This is what I do.

1. Download the newest version of the Play Store from APKMirror ([https://apkmirror.com/apk/google-inc/google-play-store/](https://apkmirror.com/apk/google-inc/google-play-store/)).
2. Rename the downloaded file to something simple, e.g. `PlayStore.apk`.
3. Move the file to the `/system/priv-app/` folder. I usually use MiXplorer ([https://apkmirror.com/apk/pishrodevs/mixplorer-hootanparsa/](https://apkmirror.com/apk/pishrodevs/mixplorer-hootanparsa/)) when doing it in a running system, or `adb push PlayStore.apk /system/priv-app/` when doing it in recovery. Also, make sure that the copied file has the same permissions as the rest of the files in that folder, which are `-rw-r--r--` or `644`.
4. Reboot the OS.

After performing these steps, you should now have a working PlayStore app. Of course, you will also need microG ([https://github.com/microg/android_packages_apps_GmsCore](https://github.com/microg/android_packages_apps_GmsCore)) in order to actually log in with your Google account.

**Comment by RLTYChq** [comment]
That's great, thanks for the help

**Comment by jkamm1985** [comment]
Hello. I know this is an old post but I wanted to post this somewhere as it's not commonly mentioned in the hopes this helps someone. Before troubleshooting, make sure your date and time is set correctly down to the minute or enable use network provided time located in Date and Time in settings. My clock was set ahead manually by three minutes due to how I use the device and that was enough to invalidate the license check. Setting that fixed my problem on Android and may work on other devices as well.
