### ISSUE TITLE
Cannot install some apps (ERROR. COULD NOT GET APP VERSION.)

### ISSUE THREAD

**Issue by ppmoses** [yeriomin/YalpStore#59]
There is one app that I could not install: com.pokemon.pokemontcg
The app finds it, but cannot download/install it. The button shows: "ERROR. COULD NOT GET APP VERSION."

**Comment by yeriomin** [comment]
I added this message to attract attention instead of letting it fail silently. Play Store doesn't return version info (which is required for download) for some apps, while still showing them in search results. Most likely this means the app is not supported on current device.

The app you mentioned is aimed at tablets, I could not install it on my smartphone, the Play Store says its incompatible on app's page.

This probably means the right solution is to hide such apps altogether.

**Comment by ppmoses** [comment]
You are right, the app is not declared as compatible with my device (I thought it was, did not check well enough, my bad).

Maybe greying out the entry in the list would work too, so people don't wonder why it's not there.
