### ISSUE TITLE
Suggests updates of same version.

### ISSUE THREAD

**Issue by 5chdn** [yeriomin/YalpStore#60]
Hi there, my yalpstore 0.6 suggests several updates for apps I installed from F-Droid. One example: Greenbits version 1.95 from F-droid, Yalp suggests to update Greenbits version 1.95 from Google play. Why?

In addition, it does not install. When I try to update the Yalp/Play version I always get the error "not installed". (Is this a separate issue?)

I'm on a google-free cyanogenmod 13.1 on a nexus 5 with f-droid.

**Comment by JonnyTech** [comment]
Apps from F-Droid are signed with a different key than those from the Play Store. Android forbids you from updating apps unless they have the same key. You must uninstall the F-Droid version before installing the Play Store one. All stores behave in the same way. If you use Play Store then you will get the same behaviour.

**Comment by 5chdn** [comment]
Thanks for clarification, that explains the error I get, however, should the same version be shown as update? Is this related to the signing?

**Comment by JonnyTech** [comment]
No, only a version number greater than the one installed should show there. What version does the applications section in Android settings tell you that is installed?

**Comment by JonnyTech** [comment]
If you select the entry in Yap store then it will show you the current version followed by the version that it will update to.

**Comment by 5chdn** [comment]
![photo_2017-02-06_17-06-29](https://cloud.githubusercontent.com/assets/15729797/22654921/a1ad9648-ec8e-11e6-8b62-8dace008007d.jpg)
![photo_2017-02-06_17-06-30](https://cloud.githubusercontent.com/assets/15729797/22654922/a1b2eeea-ec8e-11e6-8baa-5c440efed4e8.jpg)

**Comment by JonnyTech** [comment]
Looks like a bug to me, let's wait for the developer to reply..

**Comment by yeriomin** [comment]
This app uses different versioning schemes in f-droid and Play Store - version code **95** and 210301**95** respectively.

Android apps have a mandatory int `version code` which always goes up when version changes, and `version string` which is optional and can have any format the developer wants (`v1.95`, `1,95`, `version one ninety five`). Comparing strings is a bad idea. That's why I compare version codes and changing this behavior will affect other apps. I'd recommend adding this app to ignore list if it bothers you.
