### ISSUE TITLE
Android TV Support

### ISSUE THREAD

**Issue by thegithub** [yeriomin/YalpStore#62]
Any chance to support Android TV?

**Comment by yeriomin** [comment]
Seems impractical. How would you use it? Sideload it and search apps using a keyboard?

**Comment by thegithub** [comment]
Hi. Yes. Actually the app is half way working with Android TV (I'm using Nvidia TV shield to test it). I installed it using F-Droid, so yes, sideloading is the way to go. regarding the keyboard, I couldn't test it (though there is on screen keyboard) as Search does not work. I tried to make some changes to the code as well, to make the app searchable following this URL:
https://developer.android.com/training/tv/discovery/searchable.html
However, so far with no success. I broke the app by changing it's manifests, so I guess there is some extra work to be done. I think this work is feasible and short to a seasonal Android developer.
I suggest to make a prototype first, meaning: to start with sideload and using physical keyboard, we can progress from there to on-screen keyboard (I believe by making the app searchable)

**Comment by yeriomin** [comment]
I'll read more on the topic and get back to you. Thanks for writing an issue.

**Comment by thegithub** [comment]
Thank you very much. Your app is extremely cool and adding Android TV to the list of supported environments would be much appreciated :)

**Comment by yeriomin** [comment]
The "quick and dirty" solution is ready. The original app UI - the main menu with the search button - works now. Everything else worked without any modification. Even navigating the UI with just the direction buttons is possible (admittedly, not very convenient).

Implementing this properly (so that it would be seamless in the TV UI) is impossible within Yalp in its current form:
* it requires including a heavy dependency
* all of the TV-related stuff works on API=>21 only, so there would be a lot of duplication
* all of the UI would have to be rewritten

Implementation is in master. Will be out with the version 0.10.

**Comment by thegithub** [comment]
This sounds great :) I hope to get a hold on it test it as soon as possible.

**Comment by thegithub** [comment]
Best "quick and dirty" solution so far :) I built it and installed it on the TV. Seems to work perfect for me. I guess default for Done button on the "On Screen" should be "Search" so it can search as soon as you press it, but either way pressing "back" and then "search" does the thing. when I want to download and install I have to scroll down till I get the "download" button. all issues are nothing much for as I'm 100% happy with the results. Many thanks!
