### ISSUE TITLE
Hide F-Droid apps by default

### ISSUE THREAD

**Issue by Gyges88** [yeriomin/YalpStore#69]
I'd like to suggest that apps installed by F-Droid are hidden by default, since they cannot be updated anyway due to signature conflicts. Also, this is quite a bit confusing for less tech-savy folks, so that they might think the app is broken. Maybe there should be an option to show them in the settings.

**Comment by yeriomin** [comment]
It is impossible to know if an installed app comes from f-droid or not. And the apk has to be downloaded to check if there is a signature conflict. Also, f-droid app does exactly the same thing when it encounters signature mismatch (the message about the signature mismatch is taken from f-droid source).

So, this won't be done. Sorry.

**Comment by rugk** [comment]
Actually the Play Store also does it. Don't know how, however.

Can't you just maintain a list of apps installed via YalpStore and if the app is not in this list, it has been installed by a third-party (FDroid) and so offering updates is not useful and you can hide the updates, as the signature will be different anyway?
Or, if there is really no better way, at least check the signature if updates are downloaded and if it mismatched do not offer the installation to the user. (this could still nbe useful when auto-downloading of updates is enabled)

Currently it is really bad to get updates for apps installed via FDroid. A third way to solve it would be to work together with the F-Droid developers, so they offer an API to check whether an app was installed via FDroid (apparently they do not offer updates for apps installed via Google Play/Yalp, at least they have a note in the version list that this version has been installed from a different source).

In any case, please change it. This issue is annoying and blacklisting all F-Droid apps is cumbersome, error-prone (just image you blacklist the wrong app once as you thought you used F-Droid to install it, but did not do actually) and not really a solution, which scales when you have many apps.
Please reopen this issue.

**Comment by rugk** [comment]
@yeriomin Could you please reopen this issue?

**Comment by yeriomin** [comment]
@rugk 
> Can't you just maintain a list of apps installed via YalpStore

I can, but it is not a good idea considering Yalp might not be the first app to be installed - it would make all the apps installed before it unupdatable.

> it has been installed by a third-party (FDroid) and so offering updates is not useful

It **is** useful. The user just has to manually uninstall the app first. The message mentions this.

> if it mismatched do not offer the installation to the user

All user actions need to be answered, ignoring them would make the app seem broken. Notification and/or toast suit this case well.

> A third way to solve it would be to work together with the F-Droid developers, so they offer an API to check whether an app was installed via FDroid.

It is impossible in fdroid's unprivileged mode (the system installer does all the work) and already done in fdroid's privileged mode (but that's irrelevant since most people do not install privileged extension). Package's installation source **is** stored, but it can not be trusted.

> blacklisting all F-Droid apps is cumbersome

How is filling out a checkbox list cumbersome?

Existing solution is better than the solution(s) you are proposing. Making the user responsible is not a bad thing.

**Comment by rugk** [comment]
> How is filling out a checkbox list cumbersome?

Actually it is particularly bad if you have auto-download enabled. Then the app is downloaded, you get a notification, you have to delete the APK manually, you have to go into Yalp Store, select the app, tap on the menu, tap on "Ignore updates". That's really cumbersome.
Maybe an idea would be to at least include the button "ignore updates" in the notification. This would already make it easier. (And it may also delete the APK automatically!)

But if:
> Package's installation source is stored, but it can not be trusted.

…then why can't you use that? In which cases cannot it be trusted?

Making the user responsible is not bad, right, but annoying the user is bad. And I would bet that 80% of the Yalp Users also have F-Droid installed. So this issue annoys each of them. For (nearly) each new installed app from F-Droid.

In any case "ignore apps installed from F-Droid" should of course be an option and maybe even off by default if you want, but at least offer it. Or name the option "Add apps installed from F-Droid to blacklist automatically", so that users still have the choice to re-enable updates for an app.

Also, if auto-updates are enabled, you can still do this thing:
> Or, if there is really no better way, at least check the signature if updates are downloaded and if it mismatched do not offer the installation to the user.

**Comment by yeriomin** [comment]
@rugk 
> you have to go into Yalp Store, select the app, tap on the menu, tap on "Ignore updates"

There is a "Change apps black list" item in Preferences. It presents you a checkbox list of all apps on your device. You can choose all apps you want to ignore in one go.

> "ignore updates" in the notification

That is actually a good idea. Created an issue: #221

> then why can't you use that? In which cases cannot it be trusted?

Root/privileged installation is required to set package source. Most users don't have that.

> So this issue annoys each of them.

Different people often want opposite things.

Again: "ignore apps installed from F-Droid" is impossible to implement because it is impossible to reliably determine if the app was installed by F-Droid.

**Comment by rugk** [comment]
> There is a "Change apps black list" item in Preferences. It presents you a checkbox list of all apps on your device. You can choose all apps you want to ignore in one go.

Okay, this is an option if you have many F-Droid apps installed and want to blacklist them all at once, but this does not make the case easier when you've installed a new app.

> That is actually a good idea. Created an issue: #221

Yay! This is a thing, which makes it easier…

> Different people often want opposite things.

That's why it's an option.

> Again: "ignore apps installed from F-Droid" is impossible to implement because it is impossible to reliably determine if the app was installed by F-Droid.

Hmm, that's bad.

However, I think we have solved the scenarios nearly at any stage:
* old installed F-Droid apps --> blacklist via settings
* newly installed apps --> TODO
* updates found for newly installed apps --> https://github.com/yeriomin/YalpStore/issues/221

So as for the "newly installed apps" maybe you can at least detect if a new app from F-Droid has been installed? (Many other apps, such as AV apps and so one, can detect app installations) If it is detected then maybe ask the user (in a notification) whether to blacklist this app?
Example: "The app ExampleApp has been installed from F-Droid. Do you want to blacklist it in YalpStore, so updates from Google Play are not ignored?"
(of course, it should be possible to deactivate this question in the options)

**Comment by fletch31337** [comment]
Would be good to have an option to automatically whitelist apps that are installed using Yalp. That way I can ignore all F-Droid apps but allow Yalp to check for updates for Yalp installed apps without having to install, then manually whitelist it (which I can forget to do!).

**Comment by rugk** [comment]
Of you read this issue, you see, this has already been proposed. The problem is here, what should it do if you reinstall/install yalp later than most Google apps?

**Comment by fletch31337** [comment]
While this is an issue, the apps installed before Yalp can still be manually whitelisted. However, if like me, you install Yalp straight away, this is not an issue and the option can be left disabled by default if necessary.
