### ISSUE TITLE
Update dialog: enable choices for installation method

### ISSUE THREAD

**Issue by bonanza123** [yeriomin/YalpStore#87]
I can perfectly install apps using YalpStore (thanks a lot for that!), and whenever I hit the "install" button after download (automatic install is disabled) a dialog pops up where I can choose the installation tool (like a dialog asking with which tool I want to open the APK). For privacy reasons and because I still have android 4.x i'm often using [AppGuard](http://www.srt-appguard.com/en/) to install "unsafe" android apps. 

However, since some time, YalpStore doesn't issue that dialog anymore when I want to update an installed app. This results in the problem that the installation fails with a wrong signature warning (because AppGuard is manipulating the APK before install).

Therefore, I'd like to kindly request to have also the option to the select the APK-handler when updating.

**Comment by yeriomin** [comment]
@bonanza123 Yalp Store does not have permission to install apps. Technically it asks the OS to show the user the installation window. The same thing happens when you tap an apk file in your file manager. Therefore Yalp Store has no power over the installation tool dialog, and never had. The OS shows you this when you have two or more apps capable of completing the action you want (installing apps, viewing a picture, sending an email...) and none of them is chosen as default. So most likely you've chosen the system installer as the default app for installing other apps.

Try clearing default app for installing other apps.

**Comment by bonanza123** [comment]
thanks for your reply.
That's weird, because I haven't set any default APK handler (that also why upon first install of a new android app I have the dialog; and when opening an APK manually via file manager also I have the dialog).

Could you tell me where YalpStore stores it's downloaded APKs which are ready to install?

**Comment by yeriomin** [comment]
Default Downloads directory. Where the browser downloads stuff to.
