### ISSUE TITLE
Yalp Store stores unencrypted password in simple text file

### ISSUE THREAD

**Issue by teod0r** [yeriomin/YalpStore#9]
Probably, it is not the best idea

**Comment by yeriomin** [comment]
Actually I don't know which password you mean.
The one in the tests is a placeholder in case other devs want to record more test responses.
The SharedPreferences storage is secure enough, unless you both root your phone and are careless with the stuff you grant privileges to. I also added a disclaimer telling user not to use their main account.

Either way, Yalp no longer stores user passwords at all. Password is used once to get auth token.

Fixed in master, will be in v0.3.
Thanks again for writing issues!
